## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import variable as v;
import variable as v
# (Line 3) import func.trig as trg;
from func import trig as trg
# (Line 4) import func.trigadv as adv;
from func import trigadv as adv
# (Line 5) import func.sound as s;
from func import sound as s
# (Line 7) var val = 0;
val = EUDCreateVariables(1)
_IGVA([val], lambda: [0])
# (Line 10) function main(playerID)
# (Line 11) {
@EUDFunc
def f_main(playerID):
    # (Line 12) if (v.P_CountMain[playerID] >= 3)
    if EUDIf()(v.P_CountMain[playerID] >= 3):
        # (Line 13) {
        # (Line 14) trg.Debuff_Stop();
        trg.Debuff_Stop()
        # (Line 15) }
        # (Line 17) trg.Debuff_BanReturn();
    EUDEndIf()
    trg.Debuff_BanReturn()
    # (Line 19) MoveUnit(All, " Unit. Schnee", playerID, "Anywhere", "[Skill]HoldPosition");
    # (Line 21) trg.Buff_ShieldFix(1);
    DoActions(MoveUnit(All, " Unit. Schnee", playerID, "Anywhere", "[Skill]HoldPosition"))
    trg.Buff_ShieldFix(1)
    # (Line 23) if (val != 0)
    if EUDIf()(val == 0, neg=True):
        # (Line 24) s.CharacterVoice(7 + val);
        s.CharacterVoice(7 + val)
        # (Line 26) if (v.P_WaitMain[playerID] == 0)
    EUDEndIf()
    if EUDIf()(v.P_WaitMain[playerID] == 0):
        # (Line 27) {
        # (Line 28) if (v.P_CountMain[playerID] == 0)
        if EUDIf()(v.P_CountMain[playerID] == 0):
            # (Line 29) {
            # (Line 30) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 31) {
                # (Line 32) val = 3;
                val << (3)
                # (Line 34) SetDeaths(playerID, SetTo, 1, " `ShieldRecharge");
                # (Line 35) }
                DoActions(SetDeaths(playerID, SetTo, 1, " `ShieldRecharge"))
                # (Line 37) trg.Main_Wait(160);
            EUDEndIf()
            trg.Main_Wait(160)
            # (Line 39) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 41) if (v.P_LoopMain[playerID] == 30)
            if EUDIf()(v.P_LoopMain[playerID] == 30):
                # (Line 42) {
                # (Line 43) val = 4;
                val << (4)
                # (Line 45) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 46) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 47) }
                # (Line 48) }
            EUDEndIf()
            # (Line 49) else if (v.P_CountMain[playerID] == 1)
        if EUDElseIf()(v.P_CountMain[playerID] == 1):
            # (Line 50) {
            # (Line 51) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 52) {
                # (Line 53) SetSwitch("Recall - Oda", Set);
                # (Line 54) }
                DoActions(SetSwitch("Recall - Oda", Set))
                # (Line 56) if (v.P_LoopMain[playerID] == 15)
            EUDEndIf()
            if EUDIf()(v.P_LoopMain[playerID] == 15):
                # (Line 57) {
                # (Line 58) val = 5;
                val << (5)
                # (Line 59) }
                # (Line 61) trg.Main_Wait(160);
            EUDEndIf()
            trg.Main_Wait(160)
            # (Line 63) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 65) if (v.P_LoopMain[playerID] == 36)
            if EUDIf()(v.P_LoopMain[playerID] == 36):
                # (Line 66) {
                # (Line 67) val = 0;
                val << (0)
                # (Line 69) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 70) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 71) }
                # (Line 72) }
            EUDEndIf()
            # (Line 73) else if (v.P_CountMain[playerID] == 2)
        if EUDElseIf()(v.P_CountMain[playerID] == 2):
            # (Line 74) {
            # (Line 75) trg.Shape_Edge(playerID, 1, " Unit. Hoffnung 25000", 45, 3, 50);
            trg.Shape_Edge(playerID, 1, " Unit. Hoffnung 25000", 45, 3, 50)
            # (Line 76) KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID);
            # (Line 78) trg.Main_Wait(160);
            DoActions(KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID))
            trg.Main_Wait(160)
            # (Line 80) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 82) if (v.P_LoopMain[playerID] == 26)
            if EUDIf()(v.P_LoopMain[playerID] == 26):
                # (Line 83) {
                # (Line 84) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 85) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 86) }
                # (Line 87) }
            EUDEndIf()
            # (Line 88) else if (v.P_CountMain[playerID] == 3)
        if EUDElseIf()(v.P_CountMain[playerID] == 3):
            # (Line 89) {
            # (Line 90) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 91) {
                # (Line 92) trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 6, 50);
                trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 6, 50)
                # (Line 93) }
                # (Line 94) else if (v.P_LoopMain[playerID] == 2)
            if EUDElseIf()(v.P_LoopMain[playerID] == 2):
                # (Line 95) {
                # (Line 96) trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 11, 50);
                trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 11, 50)
                # (Line 97) }
                # (Line 98) else if (v.P_LoopMain[playerID] == 4)
            if EUDElseIf()(v.P_LoopMain[playerID] == 4):
                # (Line 99) {
                # (Line 100) trg.Shape_NxNSquare(playerID, 1, "40 + 1n Wraith", 11, 75);
                trg.Shape_NxNSquare(playerID, 1, "40 + 1n Wraith", 11, 75)
                # (Line 101) trg.Shape_NxNSquare(playerID, 1, " Unit. Hoffnung 25000", 11, 75);
                trg.Shape_NxNSquare(playerID, 1, " Unit. Hoffnung 25000", 11, 75)
                # (Line 103) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 104) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 105) }
                DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                # (Line 106) else if (v.P_LoopMain[playerID] == 6)
            if EUDElseIf()(v.P_LoopMain[playerID] == 6):
                # (Line 107) {
                # (Line 108) RemoveUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
                # (Line 110) trg.Shape_NxNSquare(playerID, 1, "50 + 1n Battlecruiser", 11, 75);
                DoActions(RemoveUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
                trg.Shape_NxNSquare(playerID, 1, "50 + 1n Battlecruiser", 11, 75)
                # (Line 112) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 113) Order("50 + 1n Battlecruiser", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 114) }
                DoActions(Order("50 + 1n Battlecruiser", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                # (Line 116) KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID);
            EUDEndIf()
            # (Line 117) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID);
            DoActions(KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID))
            # (Line 119) trg.Main_Wait(160);
            DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID))
            trg.Main_Wait(160)
            # (Line 121) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 123) if (v.P_LoopMain[playerID] == 8)
            if EUDIf()(v.P_LoopMain[playerID] == 8):
                # (Line 124) {
                # (Line 125) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 126) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 127) }
                # (Line 128) }
            EUDEndIf()
            # (Line 129) else if (v.P_CountMain[playerID] == 4)
        if EUDElseIf()(v.P_CountMain[playerID] == 4):
            # (Line 130) {
            # (Line 131) CreateUnit(24, "80 + 1n Guardian", dwrand() % 8 + 33, playerID);
            # (Line 132) CreateUnit(6, "40 + 1n Guardian", dwrand() % 8 + 33, playerID);
            DoActions(CreateUnit(24, "80 + 1n Guardian", f_dwrand() % 8 + 33, playerID))
            # (Line 133) SetInvincibility(Enable, "Any unit", playerID, "[Skill]Unit_Wait_ALL");
            DoActions(CreateUnit(6, "40 + 1n Guardian", f_dwrand() % 8 + 33, playerID))
            # (Line 135) var i = 0;
            DoActions(SetInvincibility(Enable, "Any unit", playerID, "[Skill]Unit_Wait_ALL"))
            i = EUDVariable()
            i << (0)
            # (Line 137) for (; i < 6; i++)
            if EUDWhile()(i >= 6, neg=True):
                def _t21():
                    i.__iadd__(1)
                # (Line 138) {
                # (Line 139) if (Bring(playerID, AtLeast, 1, "50 + 1n Battlecruiser", "Anywhere"))
                if EUDIf()(Bring(playerID, AtLeast, 1, "50 + 1n Battlecruiser", "Anywhere")):
                    # (Line 140) {
                    # (Line 141) var x = dwrand() % 20 + 10;
                    x = EUDVariable()
                    x << (f_dwrand() % 20 + 10)
                    # (Line 143) MoveLocation(v.P_LocationID[playerID], "50 + 1n Battlecruiser", playerID, "Anywhere");
                    # (Line 144) RemoveUnitAt(1, "50 + 1n Battlecruiser", "Anywhere", playerID);
                    DoActions(MoveLocation(v.P_LocationID[playerID], "50 + 1n Battlecruiser", playerID, "Anywhere"))
                    # (Line 145) MoveUnit(1, "40 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]);
                    DoActions(RemoveUnitAt(1, "50 + 1n Battlecruiser", "Anywhere", playerID))
                    # (Line 146) addloc(v.P_LocationID[playerID], x, x);
                    DoActions(MoveUnit(1, "40 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]))
                    f_addloc(v.P_LocationID[playerID], x, x)
                    # (Line 147) MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]);
                    # (Line 148) addloc(v.P_LocationID[playerID], -x, -x);
                    DoActions(MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]))
                    f_addloc(v.P_LocationID[playerID], -x, -x)
                    # (Line 149) MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]);
                    # (Line 150) addloc(v.P_LocationID[playerID], -x, x);
                    DoActions(MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]))
                    f_addloc(v.P_LocationID[playerID], -x, x)
                    # (Line 151) MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]);
                    # (Line 152) addloc(v.P_LocationID[playerID], x, -x);
                    DoActions(MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]))
                    f_addloc(v.P_LocationID[playerID], x, -x)
                    # (Line 153) MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]);
                    # (Line 154) }
                    DoActions(MoveUnit(1, "80 + 1n Guardian", playerID, "[Skill]Unit_Wait_ALL", v.P_LocationID[playerID]))
                    # (Line 155) }
                EUDEndIf()
                # (Line 157) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                EUDSetContinuePoint()
                _t21()
            EUDEndWhile()
            # (Line 158) Order("40 + 1n Guardian", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 160) KillUnitAt(All, "80 + 1n Guardian", "Anywhere", playerID);
            DoActions(Order("40 + 1n Guardian", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            # (Line 162) trg.Main_Wait(160);
            DoActions(KillUnitAt(All, "80 + 1n Guardian", "Anywhere", playerID))
            trg.Main_Wait(160)
            # (Line 164) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 166) if (v.P_LoopMain[playerID] == 25)
            if EUDIf()(v.P_LoopMain[playerID] == 25):
                # (Line 167) {
                # (Line 168) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 169) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 170) }
                # (Line 171) }
            EUDEndIf()
            # (Line 172) else if (v.P_CountMain[playerID] == 5)
        if EUDElseIf()(v.P_CountMain[playerID] == 5):
            # (Line 173) {
            # (Line 174) if (v.P_LoopMain[playerID] % 3 == 0)
            if EUDIf()(v.P_LoopMain[playerID] % 3 == 0):
                # (Line 175) {
                # (Line 176) trg.Table_Sin(playerID, 0, 40 * (v.P_LoopMain[playerID] / 3));
                trg.Table_Sin(playerID, 0, 40 * (v.P_LoopMain[playerID] // 3))
                # (Line 177) trg.Table_Cos(playerID, 0, 40 * (v.P_LoopMain[playerID] / 3));
                trg.Table_Cos(playerID, 0, 40 * (v.P_LoopMain[playerID] // 3))
                # (Line 179) var x = v.P_AngleCos[playerID];
                x = EUDVariable()
                x << (v.P_AngleCos[playerID])
                # (Line 180) var y = v.P_AngleSin[playerID];
                y = EUDVariable()
                y << (v.P_AngleSin[playerID])
                # (Line 182) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, x, y);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, x, y)
                # (Line 183) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, -x, -y);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, -x, -y)
                # (Line 184) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, -y, x);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, -y, x)
                # (Line 185) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, y, -x);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Wraith", 2, 50, y, -x)
                # (Line 187) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, x, y);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, x, y)
                # (Line 188) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -x, -y);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -x, -y)
                # (Line 189) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -y, x);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -y, x)
                # (Line 190) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, y, -x);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, y, -x)
                # (Line 191) }
                # (Line 192) else if (v.P_LoopMain[playerID] % 3 == 1)
            if EUDElseIf()(v.P_LoopMain[playerID] % 3 == 1):
                # (Line 193) {
                # (Line 194) trg.Table_Sin(playerID, 30, 40 * (v.P_LoopMain[playerID] / 3));
                trg.Table_Sin(playerID, 30, 40 * (v.P_LoopMain[playerID] // 3))
                # (Line 195) trg.Table_Cos(playerID, 30, 40 * (v.P_LoopMain[playerID] / 3));
                trg.Table_Cos(playerID, 30, 40 * (v.P_LoopMain[playerID] // 3))
                # (Line 197) var x = v.P_AngleCos[playerID];
                x = EUDVariable()
                x << (v.P_AngleCos[playerID])
                # (Line 198) var y = v.P_AngleSin[playerID];
                y = EUDVariable()
                y << (v.P_AngleSin[playerID])
                # (Line 200) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, x, y);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, x, y)
                # (Line 201) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, -x, -y);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, -x, -y)
                # (Line 202) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, -y, x);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, -y, x)
                # (Line 203) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, y, -x);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mojo", 2, 50, y, -x)
                # (Line 205) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, x, y);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, x, y)
                # (Line 206) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -x, -y);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -x, -y)
                # (Line 207) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -y, x);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -y, x)
                # (Line 208) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, y, -x);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, y, -x)
                # (Line 209) }
                # (Line 210) else if (v.P_LoopMain[playerID] % 3 == 2)
            if EUDElseIf()(v.P_LoopMain[playerID] % 3 == 2):
                # (Line 211) {
                # (Line 212) trg.Table_Sin(playerID, 60, 40 * (v.P_LoopMain[playerID] / 3));
                trg.Table_Sin(playerID, 60, 40 * (v.P_LoopMain[playerID] // 3))
                # (Line 213) trg.Table_Cos(playerID, 60, 40 * (v.P_LoopMain[playerID] / 3));
                trg.Table_Cos(playerID, 60, 40 * (v.P_LoopMain[playerID] // 3))
                # (Line 215) var x = v.P_AngleCos[playerID];
                x = EUDVariable()
                x << (v.P_AngleCos[playerID])
                # (Line 216) var y = v.P_AngleSin[playerID];
                y = EUDVariable()
                y << (v.P_AngleSin[playerID])
                # (Line 218) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, x, y);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, x, y)
                # (Line 219) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, -x, -y);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, -x, -y)
                # (Line 220) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, -y, x);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, -y, x)
                # (Line 221) adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, y, -x);
                adv.Shape_NxNSquareAt2(playerID, 1, "40 + 1n Mutalisk", 2, 50, y, -x)
                # (Line 223) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, x, y);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, x, y)
                # (Line 224) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -x, -y);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -x, -y)
                # (Line 225) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -y, x);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, -y, x)
                # (Line 226) adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, y, -x);
                adv.Shape_NxNSquareAt2(playerID, 1, " Unit. Hoffnung 25000", 2, 50, y, -x)
                # (Line 227) }
                # (Line 229) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            EUDEndIf()
            # (Line 230) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 231) Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            # (Line 232) Order("40 + 1n Mutalisk", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            # (Line 234) KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID);
            DoActions(Order("40 + 1n Mutalisk", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            # (Line 236) trg.Main_Wait(80);
            DoActions(KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID))
            trg.Main_Wait(80)
            # (Line 238) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 240) if (v.P_LoopMain[playerID] == 32)
            if EUDIf()(v.P_LoopMain[playerID] == 32):
                # (Line 241) {
                # (Line 242) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID);
                # (Line 244) v.P_CountMain[playerID] += 1;
                DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID))
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 245) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 246) }
                # (Line 247) }
            EUDEndIf()
            # (Line 248) else if (v.P_CountMain[playerID] == 6)
        if EUDElseIf()(v.P_CountMain[playerID] == 6):
            # (Line 249) {
            # (Line 250) trg.Main_Wait(3200);
            trg.Main_Wait(3200)
            # (Line 252) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 253) v.P_LoopMain[playerID] = 0;
            _ARRW(v.P_LoopMain, playerID) << (0)
            # (Line 254) }
            # (Line 255) else if (v.P_CountMain[playerID] == 7)
        if EUDElseIf()(v.P_CountMain[playerID] == 7):
            # (Line 256) {
            # (Line 257) KillUnitAt(All, "40 + 1n Lurker", "Anywhere", playerID);
            # (Line 258) KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", playerID);
            DoActions(KillUnitAt(All, "40 + 1n Lurker", "Anywhere", playerID))
            # (Line 259) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
            DoActions(KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", playerID))
            # (Line 260) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID);
            DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
            # (Line 262) SetSwitch("UiltimateSwitch", Clear);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID))
            # (Line 263) SetSwitch("Recall - Oda", Clear);
            DoActions(SetSwitch("UiltimateSwitch", Clear))
            # (Line 266) trg.SkillEnd();
            DoActions(SetSwitch("Recall - Oda", Clear))
            trg.SkillEnd()
            # (Line 267) }
            # (Line 268) }
        EUDEndIf()
        # (Line 270) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
    EUDEndIf()
    # (Line 271) }
    DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
