## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import customText as tct;
import customText as tct
# (Line 2) import Variable as v;
import Variable as v
# (Line 4) var txtPtr, btnPtr, btnPos, oldCP;
txtPtr, btnPtr, btnPos, oldCP = EUDCreateVariables(4)
# (Line 6) function NormalText(cp)
# (Line 7) {
@EUDFunc
def NormalText(cp):
    # (Line 8) switch (v.Sound_Text3[cp])
    EUDSwitch(v.Sound_Text3[cp])
    # (Line 9) {
    # (Line 10) case 3000:
    _t1 = EUDSwitchCase()
    # (Line 11) PlayWAV("Rin_01.ogg");
    if _t1(3000):
        # (Line 12) v.Sound_Text3[cp] = 0;
        DoActions(PlayWAV("Rin_01.ogg"))
        _ARRW(v.Sound_Text3, cp) << (0)
        # (Line 13) tct.print("\n\n\x13\x1BRin\n\x13\x04이 앞에 무엇이 있는 걸까?\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04이 앞에 무엇이 있는 걸까?\n\n")
        # (Line 14) break;
        EUDBreak()
        # (Line 15) case 3001:
    _t2 = EUDSwitchCase()
    # (Line 16) PlayWAV("Rin_02.ogg");
    if _t2(3001):
        # (Line 17) v.Sound_Text3[cp] = 0;
        DoActions(PlayWAV("Rin_02.ogg"))
        _ARRW(v.Sound_Text3, cp) << (0)
        # (Line 18) tct.print("\n\n\x13\x1BRin\n\x13\x04언제부턴가, 생각하지 않게 됐다\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04언제부턴가, 생각하지 않게 됐다\n\n")
        # (Line 19) break;
        EUDBreak()
        # (Line 20) case 3002:
    _t3 = EUDSwitchCase()
    # (Line 21) PlayWAV("Rin_03.ogg");
    if _t3(3002):
        # (Line 22) v.Sound_Text3[cp] = 0;
        DoActions(PlayWAV("Rin_03.ogg"))
        _ARRW(v.Sound_Text3, cp) << (0)
        # (Line 23) tct.print("\n\n\x13\x1BRin\n\x13\x04생각하는 방법... 그것조차 잊어버린 걸지도\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04생각하는 방법... 그것조차 잊어버린 걸지도\n\n")
        # (Line 24) break;
        EUDBreak()
        # (Line 25) case 3003:
    _t4 = EUDSwitchCase()
    # (Line 26) PlayWAV("Rin_04.ogg");
    if _t4(3003):
        # (Line 27) v.Sound_Text3[cp] = 0;
        DoActions(PlayWAV("Rin_04.ogg"))
        _ARRW(v.Sound_Text3, cp) << (0)
        # (Line 28) tct.print("\n\n\x13\x1BRin\n\x13\x04변하지 않는, 나만의 세계가 매일매일 계속된다\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04변하지 않는, 나만의 세계가 매일매일 계속된다\n\n")
        # (Line 29) break;
        EUDBreak()
        # (Line 30) case 3004:
    _t5 = EUDSwitchCase()
    # (Line 31) PlayWAV("Rin_05.ogg");
    if _t5(3004):
        # (Line 32) v.Sound_Text3[cp] = 0;
        DoActions(PlayWAV("Rin_05.ogg"))
        _ARRW(v.Sound_Text3, cp) << (0)
        # (Line 33) tct.print("\n\n\x13\x1BRin\n\x13\x04하지만 외롭지는 않아\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04하지만 외롭지는 않아\n\n")
        # (Line 34) break;
        EUDBreak()
        # (Line 35) case 3005:
    _t6 = EUDSwitchCase()
    # (Line 36) PlayWAV("Rin_06.ogg");
    if _t6(3005):
        # (Line 37) v.Sound_Text3[cp] = 0;
        DoActions(PlayWAV("Rin_06.ogg"))
        _ARRW(v.Sound_Text3, cp) << (0)
        # (Line 38) tct.print("\n\n\x13\x1BRin\n\x13\x04별 것 아니니까\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04별 것 아니니까\n\n")
        # (Line 39) break;
        EUDBreak()
        # (Line 40) }
    # (Line 41) }
    EUDEndSwitch()
    # (Line 43) function UiltimateText(cp)

# (Line 44) {
@EUDFunc
def UiltimateText(cp):
    # (Line 45) switch (v.Sound_Text_Uilti[cp])
    EUDSwitch(v.Sound_Text_Uilti[cp])
    # (Line 46) {
    # (Line 47) case 15000:
    _t1 = EUDSwitchCase()
    # (Line 48) PlayWAV("Rin_Ult.ogg");
    if _t1(15000):
        # (Line 49) v.Sound_Text_Uilti[cp] = 0;
        DoActions(PlayWAV("Rin_Ult.ogg"))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 50) break;
        EUDBreak()
        # (Line 51) case 15001:
    _t2 = EUDSwitchCase()
    # (Line 52) txtPtr = dwread_epd(EPD(0x640B58));
    if _t2(15001):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 53) tct.print("\n\n\x13\x1BRin\n\x13\x04추억이, 슬픈 것이었다고 해도\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04추억이, 슬픈 것이었다고 해도\n\n")
        # (Line 54) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 55) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 56) break;
        EUDBreak()
        # (Line 57) case 15002:
    _t3 = EUDSwitchCase()
    # (Line 58) txtPtr = dwread_epd(EPD(0x640B58));
    if _t3(15002):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 59) tct.print("\n\n\x13\x1BRin\n\x13\x04미래를 믿으며 나아가는 거야\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04미래를 믿으며 나아가는 거야\n\n")
        # (Line 60) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 61) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 62) break;
        EUDBreak()
        # (Line 63) case 15003:
    _t4 = EUDSwitchCase()
    # (Line 64) txtPtr = dwread_epd(EPD(0x640B58));
    if _t4(15003):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 65) tct.print("\n\n\x13\x1BRin\n\x13\x04외로움을 깨달아서\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04외로움을 깨달아서\n\n")
        # (Line 66) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 67) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 68) break;
        EUDBreak()
        # (Line 69) case 15004:
    _t5 = EUDSwitchCase()
    # (Line 70) txtPtr = dwread_epd(EPD(0x640B58));
    if _t5(15004):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 71) tct.print("\n\n\x13\x1BRin\n\x13\x04좌절하고 싶어져도\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04좌절하고 싶어져도\n\n")
        # (Line 72) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 73) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 74) break;
        EUDBreak()
        # (Line 75) case 15005:
    _t6 = EUDSwitchCase()
    # (Line 76) txtPtr = dwread_epd(EPD(0x640B58));
    if _t6(15005):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 77) tct.print("\n\n\x13\x1BRin\n\x13\x04당신 덕분에\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04당신 덕분에\n\n")
        # (Line 78) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 79) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 80) break;
        EUDBreak()
        # (Line 81) case 15006:
    _t7 = EUDSwitchCase()
    # (Line 82) txtPtr = dwread_epd(EPD(0x640B58));
    if _t7(15006):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 83) tct.print("\n\n\x13\x1BRin\n\x13\x04기억해내서\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04기억해내서\n\n")
        # (Line 84) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 85) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 86) break;
        EUDBreak()
        # (Line 87) case 15007:
    _t8 = EUDSwitchCase()
    # (Line 88) txtPtr = dwread_epd(EPD(0x640B58));
    if _t8(15007):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 89) tct.print("\n\n\x13\x1BRin\n\x13\x04강해질 수 있는 거야\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04강해질 수 있는 거야\n\n")
        # (Line 90) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 91) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 92) break;
        EUDBreak()
        # (Line 93) case 15008:
    _t9 = EUDSwitchCase()
    # (Line 94) txtPtr = dwread_epd(EPD(0x640B58));
    if _t9(15008):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 95) tct.print("\n\n\x13\x1BRin\n\x13\x04혼자가 아니라고...\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04혼자가 아니라고...\n\n")
        # (Line 96) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 97) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 98) break;
        EUDBreak()
        # (Line 99) case 15009:
    _t10 = EUDSwitchCase()
    # (Line 100) txtPtr = dwread_epd(EPD(0x640B58));
    if _t10(15009):
        txtPtr << (f_dwread_epd(EPD(0x640B58)))
        # (Line 101) tct.print("\n\n\x13\x1BRin\n\x13\x04당신 덕분에...\n\n");
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04당신 덕분에...\n\n")
        # (Line 102) SetMemory(0x640B58, SetTo, txtPtr);
        # (Line 103) v.Sound_Text_Uilti[cp] = 0;
        DoActions(SetMemory(0x640B58, SetTo, txtPtr))
        _ARRW(v.Sound_Text_Uilti, cp) << (0)
        # (Line 104) break;
        EUDBreak()
        # (Line 105) }
    # (Line 106) }
    EUDEndSwitch()
    # (Line 108) function UniqueText(cp)

# (Line 109) {
@EUDFunc
def UniqueText(cp):
    # (Line 110) switch (v.Sound_Text_Uniq[cp])
    EUDSwitch(v.Sound_Text_Uniq[cp])
    # (Line 111) {
    # (Line 112) case 15000:
    _t1 = EUDSwitchCase()
    # (Line 113) tct.print("\n\n\x13\x1BRin\n\x13\x04고마워요...\n\n");
    if _t1(15000):
        tct.f_print("\n\n\x13\x1BRin\n\x13\x04고마워요...\n\n")
        # (Line 114) PlayWAV("Rin_Unique.ogg");
        # (Line 115) v.Sound_Text_Uniq[cp] = 0;
        DoActions(PlayWAV("Rin_Unique.ogg"))
        _ARRW(v.Sound_Text_Uniq, cp) << (0)
        # (Line 116) break;
        EUDBreak()
        # (Line 117) }
    # (Line 118) }
    EUDEndSwitch()
