## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _RELIMP(path, mod_name):
    import inspect, pathlib, importlib.util
    p = pathlib.Path(inspect.getabsfile(inspect.currentframe())).parent
    for s in path.split("."):
        if s == "":  p = p.parent
        else:  p = p / s
    try:
        spec = importlib.util.spec_from_file_location(mod_name, p / (mod_name + ".py"))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    except FileNotFoundError:
        loader = EPSLoader(mod_name, str(p / (mod_name + ".eps")))
        spec = importlib.util.spec_from_loader(mod_name, loader)
        module = loader.create_module(spec)
        loader.exec_module(module)
    return module

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import variable as v;
import variable as v
# (Line 3) import func.trig as trg;
from func import trig as trg
# (Line 4) import func.trigadv as adv;
from func import trigadv as adv
# (Line 5) import func.sound as s;
from func import sound as s
# (Line 7) function main(playerID)
# (Line 8) {
@EUDFunc
def f_main(playerID):
    # (Line 9) MoveLocation("24.Nanami_Bozo", v.P_UnitID[playerID], playerID, "Anywhere");
    # (Line 11) if (v.P_WaitMain[playerID] == 0)
    DoActions(MoveLocation("24.Nanami_Bozo", v.P_UnitID[playerID], playerID, "Anywhere"))
    if EUDIf()(v.P_WaitMain[playerID] == 0):
        # (Line 12) {
        # (Line 13) if (v.P_CountMain[playerID] == 0)
        if EUDIf()(v.P_CountMain[playerID] == 0):
            # (Line 14) {
            # (Line 15) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 16) {
                # (Line 17) if (playerID < 3) SetSwitch("Passive - Nanami1", Set);
                if EUDIf()(playerID >= 3, neg=True):
                    # (Line 18) else SetSwitch("Passive - Nanami2", Set);
                    DoActions(SetSwitch("Passive - Nanami1", Set))
                if EUDElse()():
                    # (Line 20) adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, -100, 100);
                    DoActions(SetSwitch("Passive - Nanami2", Set))
                EUDEndIf()
                adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, -100, 100)
                # (Line 21) trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", -100, 100);
                trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", -100, 100)
                # (Line 23) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 24) Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 25) Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                # (Line 27) trg.Main_Wait(160);
                DoActions(Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(160)
                # (Line 29) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 30) }
                # (Line 31) else if (v.P_LoopMain[playerID] == 1)
            if EUDElseIf()(v.P_LoopMain[playerID] == 1):
                # (Line 32) {
                # (Line 33) KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID);
                # (Line 35) adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, 100, -100);
                DoActions(KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID))
                adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, 100, -100)
                # (Line 36) trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", 100, -100);
                trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", 100, -100)
                # (Line 38) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 39) Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 40) Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                # (Line 42) trg.Main_Wait(160);
                DoActions(Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(160)
                # (Line 44) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 45) }
                # (Line 46) else if (v.P_LoopMain[playerID] == 2)
            if EUDElseIf()(v.P_LoopMain[playerID] == 2):
                # (Line 47) {
                # (Line 48) KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID);
                # (Line 50) adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, 100, 100);
                DoActions(KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID))
                adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, 100, 100)
                # (Line 51) trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", 100, 100);
                trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", 100, 100)
                # (Line 53) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 54) Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 55) Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                # (Line 57) trg.Main_Wait(160);
                DoActions(Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(160)
                # (Line 59) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 60) }
                # (Line 61) else if (v.P_LoopMain[playerID] == 3)
            if EUDElseIf()(v.P_LoopMain[playerID] == 3):
                # (Line 62) {
                # (Line 63) KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID);
                # (Line 65) adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, -100, -100);
                DoActions(KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID))
                adv.Shape_NxNSquareAt2(playerID, 1, "60 + 1n Danimoth", 2, 50, -100, -100)
                # (Line 66) trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", -100, -100);
                trg.Shape_Dot(playerID, 1, "60 + 1n Dragoon", -100, -100)
                # (Line 68) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 69) Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 70) Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                # (Line 72) trg.Main_Wait(160);
                DoActions(Order("60 + 1n Dragoon", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(160)
                # (Line 74) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 75) }
                # (Line 76) else if (v.P_LoopMain[playerID] == 4)
            if EUDElseIf()(v.P_LoopMain[playerID] == 4):
                # (Line 77) {
                # (Line 78) KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID);
                # (Line 80) trg.Main_Wait(400);
                DoActions(KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID))
                trg.Main_Wait(400)
                # (Line 82) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 83) }
                # (Line 84) else if (v.P_LoopMain[playerID] == 5)
            if EUDElseIf()(v.P_LoopMain[playerID] == 5):
                # (Line 85) {
                # (Line 86) trg.Table_Sin(playerID, 22, 75);
                trg.Table_Sin(playerID, 22, 75)
                # (Line 87) trg.Table_Cos(playerID, 22, 75);
                trg.Table_Cos(playerID, 22, 75)
                # (Line 89) trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 90) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                # (Line 92) trg.Shape_Square(playerID, 1, "40 + 1n Mojo", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "40 + 1n Mojo", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 93) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 94) Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 96) trg.Main_Wait(320);
                DoActions(Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(320)
                # (Line 98) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 99) }
                # (Line 100) else if (v.P_LoopMain[playerID] == 6)
            if EUDElseIf()(v.P_LoopMain[playerID] == 6):
                # (Line 101) {
                # (Line 102) trg.Table_Sin(playerID, 67, 125);
                trg.Table_Sin(playerID, 67, 125)
                # (Line 103) trg.Table_Cos(playerID, 67, 125);
                trg.Table_Cos(playerID, 67, 125)
                # (Line 105) trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 106) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                # (Line 108) trg.Shape_Square(playerID, 1, "60 + 1n Danimoth", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "60 + 1n Danimoth", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 109) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 110) Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 112) trg.Main_Wait(320);
                DoActions(Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(320)
                # (Line 114) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 115) }
                # (Line 116) else if (v.P_LoopMain[playerID] == 7)
            if EUDElseIf()(v.P_LoopMain[playerID] == 7):
                # (Line 117) {
                # (Line 118) trg.Table_Sin(playerID, 22, 175);
                trg.Table_Sin(playerID, 22, 175)
                # (Line 119) trg.Table_Cos(playerID, 22, 175);
                trg.Table_Cos(playerID, 22, 175)
                # (Line 121) trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 122) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                # (Line 124) trg.Shape_Square(playerID, 1, "40 + 1n Mojo", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "40 + 1n Mojo", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 125) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 126) Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 128) trg.Main_Wait(320);
                DoActions(Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(320)
                # (Line 130) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 131) }
                # (Line 132) else if (v.P_LoopMain[playerID] == 8)
            if EUDElseIf()(v.P_LoopMain[playerID] == 8):
                # (Line 133) {
                # (Line 134) trg.Table_Sin(playerID, 67, 225);
                trg.Table_Sin(playerID, 67, 225)
                # (Line 135) trg.Table_Cos(playerID, 67, 225);
                trg.Table_Cos(playerID, 67, 225)
                # (Line 137) trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 138) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                # (Line 140) trg.Shape_Square(playerID, 1, "60 + 1n Danimoth", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "60 + 1n Danimoth", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 141) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                # (Line 142) Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 144) trg.Main_Wait(320);
                DoActions(Order("60 + 1n Danimoth", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(320)
                # (Line 146) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 147) }
                # (Line 148) else if (v.P_LoopMain[playerID] == 9)
            if EUDElseIf()(v.P_LoopMain[playerID] == 9):
                # (Line 149) {
                # (Line 150) trg.Table_Sin(playerID, 22, 250);
                trg.Table_Sin(playerID, 22, 250)
                # (Line 151) trg.Table_Cos(playerID, 22, 250);
                trg.Table_Cos(playerID, 22, 250)
                # (Line 153) trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 154) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                # (Line 156) trg.Shape_Square(playerID, 1, "40 + 1n Gantrithor", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "40 + 1n Gantrithor", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 157) ModifyUnitHangarCount(2, All, "40 + 1n Gantrithor", CurrentPlayer, "Anywhere");
                # (Line 158) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                DoActions(ModifyUnitHangarCount(2, All, "40 + 1n Gantrithor", CurrentPlayer, "Anywhere"))
                # (Line 159) Order("40 + 1n Gantrithor", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 161) trg.Main_Wait(320);
                DoActions(Order("40 + 1n Gantrithor", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(320)
                # (Line 163) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 164) }
                # (Line 165) else if (v.P_LoopMain[playerID] == 10)
            if EUDElseIf()(v.P_LoopMain[playerID] == 10):
                # (Line 166) {
                # (Line 167) trg.Table_Sin(playerID, 67, 275);
                trg.Table_Sin(playerID, 67, 275)
                # (Line 168) trg.Table_Cos(playerID, 67, 275);
                trg.Table_Cos(playerID, 67, 275)
                # (Line 170) trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                trg.Shape_Square(playerID, 1, "100 + 1n Dragoon", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 171) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                # (Line 173) trg.Shape_Square(playerID, 1, "40 + 1n Gantrithor", v.P_AngleCos[playerID], v.P_AngleSin[playerID]);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "40 + 1n Gantrithor", v.P_AngleCos[playerID], v.P_AngleSin[playerID])
                # (Line 174) ModifyUnitHangarCount(2, All, "40 + 1n Gantrithor", CurrentPlayer, "Anywhere");
                # (Line 175) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
                DoActions(ModifyUnitHangarCount(2, All, "40 + 1n Gantrithor", CurrentPlayer, "Anywhere"))
                # (Line 176) Order("40 + 1n Gantrithor", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
                DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
                # (Line 178) trg.Main_Wait(720);
                DoActions(Order("40 + 1n Gantrithor", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
                trg.Main_Wait(720)
                # (Line 180) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 181) }
                # (Line 182) else if (v.P_LoopMain[playerID] == 11)
            if EUDElseIf()(v.P_LoopMain[playerID] == 11):
                # (Line 183) {
                # (Line 184) trg.Main_Wait(80);
                trg.Main_Wait(80)
                # (Line 186) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 187) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 188) }
                # (Line 189) }
            EUDEndIf()
            # (Line 190) else if (v.P_CountMain[playerID] == 1)
        if EUDElseIf()(v.P_CountMain[playerID] == 1):
            # (Line 191) {
            # (Line 192) if (v.P_LoopMain[playerID] < 8)
            if EUDIf()(v.P_LoopMain[playerID] >= 8, neg=True):
                # (Line 193) {
                # (Line 220) trg.Main_Wait(160);
                trg.Main_Wait(160)
                # (Line 222) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 223) }
                # (Line 224) else if (v.P_LoopMain[playerID] == 8)
            if EUDElseIf()(v.P_LoopMain[playerID] == 8):
                # (Line 225) {
                # (Line 226) trg.Main_Wait(2160);
                trg.Main_Wait(2160)
                # (Line 228) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 229) }
                # (Line 230) else if (v.P_LoopMain[playerID] == 9)
            if EUDElseIf()(v.P_LoopMain[playerID] == 9):
                # (Line 231) {
                # (Line 232) trg.Main_Wait(80);
                trg.Main_Wait(80)
                # (Line 234) s.CharacterVoice(9);
                s.CharacterVoice(9)
                # (Line 236) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 237) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 238) }
                # (Line 240) }
            EUDEndIf()
            # (Line 241) else if (v.P_CountMain[playerID] == 2)
        if EUDElseIf()(v.P_CountMain[playerID] == 2):
            # (Line 242) {
            # (Line 243) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 244) {
                # (Line 245) KillUnitAt(All, "40 + 1n Gantrithor", "Anywhere", playerID);
                # (Line 247) trg.Main_Wait(1600);
                DoActions(KillUnitAt(All, "40 + 1n Gantrithor", "Anywhere", playerID))
                trg.Main_Wait(1600)
                # (Line 249) v.P_LoopMain[playerID] += 1;
                _ARRW(v.P_LoopMain, playerID).__iadd__(1)
                # (Line 250) }
                # (Line 251) else if (v.P_LoopMain[playerID] == 1)
            if EUDElseIf()(v.P_LoopMain[playerID] == 1):
                # (Line 252) {
                # (Line 253) KillUnitAt(All, "60 + 1n Dragoon", "Anywhere", playerID);
                # (Line 255) trg.Main_Wait(1600);
                DoActions(KillUnitAt(All, "60 + 1n Dragoon", "Anywhere", playerID))
                trg.Main_Wait(1600)
                # (Line 257) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 258) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 259) }
                # (Line 261) }
            EUDEndIf()
            # (Line 263) else if (v.P_CountMain[playerID] == 3)
        if EUDElseIf()(v.P_CountMain[playerID] == 3):
            # (Line 264) {
            # (Line 265) KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID);
            # (Line 266) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID);
            DoActions(KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", playerID))
            # (Line 267) KillUnitAt(All, "60 + 1n High Templar", "Anywhere", playerID);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID))
            # (Line 268) KillUnitAt(All, "40 + 1n Zealot", "Anywhere", playerID);
            DoActions(KillUnitAt(All, "60 + 1n High Templar", "Anywhere", playerID))
            # (Line 269) SetSwitch("Passive - Nanami1", Clear);
            DoActions(KillUnitAt(All, "40 + 1n Zealot", "Anywhere", playerID))
            # (Line 270) SetSwitch("Passive - Nanami2", Clear);
            DoActions(SetSwitch("Passive - Nanami1", Clear))
            # (Line 272) trg.SkillEnd();
            DoActions(SetSwitch("Passive - Nanami2", Clear))
            trg.SkillEnd()
            # (Line 273) }
            # (Line 274) }
        EUDEndIf()
        # (Line 275) if (v.P_WaitSub1[playerID] == 0)
    EUDEndIf()
    if EUDIf()(v.P_WaitSub1[playerID] == 0):
        # (Line 276) {
        # (Line 277) if (v.P_CountMain[playerID] < 3)
        if EUDIf()(v.P_CountMain[playerID] >= 3, neg=True):
            # (Line 278) {
            # (Line 279) if (v.P_CountSub1[playerID] == 0)
            if EUDIf()(v.P_CountSub1[playerID] == 0):
                # (Line 280) {
                # (Line 281) trg.Shape_Square(playerID, 1, " Unit. Schnee", 75, 75);
                trg.Shape_Square(playerID, 1, " Unit. Schnee", 75, 75)
                # (Line 283) KillUnitAt(All, " Unit. Schnee", "Anywhere", playerID);
                # (Line 285) trg.Sub1_Wait(160);
                DoActions(KillUnitAt(All, " Unit. Schnee", "Anywhere", playerID))
                trg.Sub1_Wait(160)
                # (Line 287) v.P_CountSub1[playerID] += 1;
                _ARRW(v.P_CountSub1, playerID).__iadd__(1)
                # (Line 288) }
                # (Line 289) else if (v.P_CountSub1[playerID] == 1)
            if EUDElseIf()(v.P_CountSub1[playerID] == 1):
                # (Line 290) {
                # (Line 291) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 150, 0);
                trg.Shape_Square(playerID, 1, "60 + 1n Archon", 150, 0)
                # (Line 293) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
                # (Line 295) trg.Sub1_Wait(160);
                DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
                trg.Sub1_Wait(160)
                # (Line 297) v.P_CountSub1[playerID] += 1;
                _ARRW(v.P_CountSub1, playerID).__iadd__(1)
                # (Line 298) }
                # (Line 299) else if (v.P_CountSub1[playerID] == 2)
            if EUDElseIf()(v.P_CountSub1[playerID] == 2):
                # (Line 300) {
                # (Line 301) trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 150, 75);
                trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 150, 75)
                # (Line 303) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
                # (Line 305) trg.Sub1_Wait(160);
                DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
                trg.Sub1_Wait(160)
                # (Line 307) v.P_CountSub1[playerID] += 1;
                _ARRW(v.P_CountSub1, playerID).__iadd__(1)
                # (Line 308) }
                # (Line 309) else if (v.P_CountSub1[playerID] == 3)
            if EUDElseIf()(v.P_CountSub1[playerID] == 3):
                # (Line 310) {
                # (Line 311) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 150, 150);
                trg.Shape_Square(playerID, 1, "60 + 1n Archon", 150, 150)
                # (Line 313) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
                # (Line 315) trg.Sub1_Wait(160);
                DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
                trg.Sub1_Wait(160)
                # (Line 317) v.P_CountSub1[playerID] += 1;
                _ARRW(v.P_CountSub1, playerID).__iadd__(1)
                # (Line 318) }
                # (Line 319) else if (v.P_CountSub1[playerID] == 4)
            if EUDElseIf()(v.P_CountSub1[playerID] == 4):
                # (Line 320) {
                # (Line 321) trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 75, 150);
                trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 75, 150)
                # (Line 323) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
                # (Line 325) trg.Sub1_Wait(160);
                DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
                trg.Sub1_Wait(160)
                # (Line 327) v.P_CountSub1[playerID] = 0;
                _ARRW(v.P_CountSub1, playerID) << (0)
                # (Line 328) }
                # (Line 329) }
            EUDEndIf()
            # (Line 330) }
        EUDEndIf()
        # (Line 331) if (v.P_WaitSub2[playerID] == 0)
    EUDEndIf()
    if EUDIf()(v.P_WaitSub2[playerID] == 0):
        # (Line 332) {
        # (Line 333) if (v.P_CountMain[playerID] < 1)
        if EUDIf()(v.P_CountMain[playerID] >= 1, neg=True):
            # (Line 334) {
            # (Line 335) if (v.P_CountSub2[playerID] == 8) v.P_CountSub2[playerID] = 0;
            if EUDIf()(v.P_CountSub2[playerID] == 8):
                _ARRW(v.P_CountSub2, playerID) << (0)
                # (Line 336) if (v.P_CountSub2[playerID] < 4)
            EUDEndIf()
            if EUDIf()(v.P_CountSub2[playerID] >= 4, neg=True):
                # (Line 337) {
                # (Line 338) trg.Shape_Dot(playerID, 1, " Unit. Schnee", 160 - 40 * v.P_CountSub2[playerID], 40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, " Unit. Schnee", 160 - 40 * v.P_CountSub2[playerID], 40 * v.P_CountSub2[playerID])
                # (Line 339) trg.Shape_Dot(playerID, 1, " Unit. Schnee", -160 + 40 * v.P_CountSub2[playerID], -40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, " Unit. Schnee", -160 + 40 * v.P_CountSub2[playerID], -40 * v.P_CountSub2[playerID])
                # (Line 340) trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", -40 * v.P_CountSub2[playerID], 160 - 40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", -40 * v.P_CountSub2[playerID], 160 - 40 * v.P_CountSub2[playerID])
                # (Line 341) trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", 40 * v.P_CountSub2[playerID], -160 + 40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", 40 * v.P_CountSub2[playerID], -160 + 40 * v.P_CountSub2[playerID])
                # (Line 343) KillUnitAt(All, " Unit. Schnee", "Anywhere", playerID);
                # (Line 344) KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", playerID);
                DoActions(KillUnitAt(All, " Unit. Schnee", "Anywhere", playerID))
                # (Line 346) trg.Sub2_Wait(320);
                DoActions(KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", playerID))
                trg.Sub2_Wait(320)
                # (Line 348) v.P_CountSub2[playerID] += 1;
                _ARRW(v.P_CountSub2, playerID).__iadd__(1)
                # (Line 349) }
                # (Line 350) else if (v.P_CountSub2[playerID] < 8)
            if EUDElseIf()(v.P_CountSub2[playerID] >= 8, neg=True):
                # (Line 351) {
                # (Line 352) trg.Shape_Dot(playerID, 1, " Unit. Schnee", -40 * (v.P_CountSub2[playerID] - 4), 160 - 40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, " Unit. Schnee", -40 * (v.P_CountSub2[playerID] - 4), 160 - 40 * (v.P_CountSub2[playerID] - 4))
                # (Line 353) trg.Shape_Dot(playerID, 1, " Unit. Schnee", 40 * (v.P_CountSub2[playerID] - 4), -160 + 40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, " Unit. Schnee", 40 * (v.P_CountSub2[playerID] - 4), -160 + 40 * (v.P_CountSub2[playerID] - 4))
                # (Line 354) trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", 160 - 40 * (v.P_CountSub2[playerID] - 4), 40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", 160 - 40 * (v.P_CountSub2[playerID] - 4), 40 * (v.P_CountSub2[playerID] - 4))
                # (Line 355) trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", -160 + 40 * (v.P_CountSub2[playerID] - 4), -40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, "40 + 3n Zeratul", -160 + 40 * (v.P_CountSub2[playerID] - 4), -40 * (v.P_CountSub2[playerID] - 4))
                # (Line 357) KillUnitAt(All, " Unit. Schnee", "Anywhere", playerID);
                # (Line 358) KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", playerID);
                DoActions(KillUnitAt(All, " Unit. Schnee", "Anywhere", playerID))
                # (Line 360) trg.Sub2_Wait(320);
                DoActions(KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", playerID))
                trg.Sub2_Wait(320)
                # (Line 362) v.P_CountSub2[playerID] += 1;
                _ARRW(v.P_CountSub2, playerID).__iadd__(1)
                # (Line 363) }
                # (Line 364) }
            EUDEndIf()
            # (Line 365) else if (v.P_CountMain[playerID] < 2 && v.P_CountMain[playerID] > 0)
        if EUDElseIf()(EUDSCAnd()(v.P_CountMain[playerID] >= 2, neg=True)(v.P_CountMain[playerID] <= 0, neg=True)()):
            # (Line 366) {
            # (Line 367) if (v.P_CountSub2[playerID] == 8) v.P_CountSub2[playerID] = 0;
            if EUDIf()(v.P_CountSub2[playerID] == 8):
                _ARRW(v.P_CountSub2, playerID) << (0)
                # (Line 368) if (v.P_CountSub2[playerID] < 4)
            EUDEndIf()
            if EUDIf()(v.P_CountSub2[playerID] >= 4, neg=True):
                # (Line 369) {
                # (Line 370) trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", 160 - 40 * v.P_CountSub2[playerID], 40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", 160 - 40 * v.P_CountSub2[playerID], 40 * v.P_CountSub2[playerID])
                # (Line 371) trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", -160 + 40 * v.P_CountSub2[playerID], -40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", -160 + 40 * v.P_CountSub2[playerID], -40 * v.P_CountSub2[playerID])
                # (Line 372) trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", -40 * v.P_CountSub2[playerID], 160 - 40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", -40 * v.P_CountSub2[playerID], 160 - 40 * v.P_CountSub2[playerID])
                # (Line 373) trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", 40 * v.P_CountSub2[playerID], -160 + 40 * v.P_CountSub2[playerID]);
                trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", 40 * v.P_CountSub2[playerID], -160 + 40 * v.P_CountSub2[playerID])
                # (Line 375) KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID);
                # (Line 376) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                DoActions(KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID))
                # (Line 378) trg.Sub2_Wait(320);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Sub2_Wait(320)
                # (Line 380) v.P_CountSub2[playerID] += 1;
                _ARRW(v.P_CountSub2, playerID).__iadd__(1)
                # (Line 381) }
                # (Line 382) else if (v.P_CountSub2[playerID] < 8)
            if EUDElseIf()(v.P_CountSub2[playerID] >= 8, neg=True):
                # (Line 383) {
                # (Line 384) trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", -40 * (v.P_CountSub2[playerID] - 4), 160 - 40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", -40 * (v.P_CountSub2[playerID] - 4), 160 - 40 * (v.P_CountSub2[playerID] - 4))
                # (Line 385) trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", 40 * (v.P_CountSub2[playerID] - 4), -160 + 40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, " Unit. Hoffnung 25000", 40 * (v.P_CountSub2[playerID] - 4), -160 + 40 * (v.P_CountSub2[playerID] - 4))
                # (Line 386) trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", 160 - 40 * (v.P_CountSub2[playerID] - 4), 40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", 160 - 40 * (v.P_CountSub2[playerID] - 4), 40 * (v.P_CountSub2[playerID] - 4))
                # (Line 387) trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", -160 + 40 * (v.P_CountSub2[playerID] - 4), -40 * (v.P_CountSub2[playerID] - 4));
                trg.Shape_Dot(playerID, 1, "100 + 1n Dragoon", -160 + 40 * (v.P_CountSub2[playerID] - 4), -40 * (v.P_CountSub2[playerID] - 4))
                # (Line 389) KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID);
                # (Line 390) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID);
                DoActions(KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID))
                # (Line 392) trg.Sub2_Wait(320);
                DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", playerID))
                trg.Sub2_Wait(320)
                # (Line 394) v.P_CountSub2[playerID] += 1;
                _ARRW(v.P_CountSub2, playerID).__iadd__(1)
                # (Line 395) }
                # (Line 396) }
            EUDEndIf()
            # (Line 399) }
        EUDEndIf()
        # (Line 400) }
    EUDEndIf()
