## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import variable as v;
import variable as v
# (Line 3) import func.trig as trg;
from func import trig as trg
# (Line 5) function main(playerID)
# (Line 6) {
@EUDFunc
def f_main(playerID):
    # (Line 7) MoveUnit(All, "40 + 1n Guardian", playerID, "Anywhere", "[Skill]HoldPosition");
    # (Line 9) if (v.P_WaitMain[playerID] == 0)
    DoActions(MoveUnit(All, "40 + 1n Guardian", playerID, "Anywhere", "[Skill]HoldPosition"))
    if EUDIf()(v.P_WaitMain[playerID] == 0):
        # (Line 10) {
        # (Line 11) switch(v.P_CountMain[playerID])
        EUDSwitch(v.P_CountMain[playerID])
        # (Line 12) {
        # (Line 13) case 0:
        _t2 = EUDSwitchCase()
        # (Line 14) trg.Shape_Square(playerID, 1, "Torrasque", 48, 48);
        if _t2(0):
            trg.Shape_Square(playerID, 1, "Torrasque", 48, 48)
            # (Line 15) KillUnitAt(All, "Torrasque", "Anywhere", playerID);
            # (Line 16) trg.Main_Wait(0);
            DoActions(KillUnitAt(All, "Torrasque", "Anywhere", playerID))
            trg.Main_Wait(0)
            # (Line 17) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 18) break;
            EUDBreak()
            # (Line 19) case 1:
        _t3 = EUDSwitchCase()
        # (Line 20) trg.Shape_Square(playerID, 1, "40 + 1n Guardian", 96, 96);
        if _t3(1):
            trg.Shape_Square(playerID, 1, "40 + 1n Guardian", 96, 96)
            # (Line 21) trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 96, 96);
            trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 96, 96)
            # (Line 22) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
            # (Line 23) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
            # (Line 24) Order("40 + 1n Guardian", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 25) trg.Main_Wait(0);
            DoActions(Order("40 + 1n Guardian", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            trg.Main_Wait(0)
            # (Line 26) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 27) break;
            EUDBreak()
            # (Line 28) case 2:
        _t4 = EUDSwitchCase()
        # (Line 29) trg.Shape_Square(playerID, 1, "Torrasque", 64, 0);
        if _t4(2):
            trg.Shape_Square(playerID, 1, "Torrasque", 64, 0)
            # (Line 30) KillUnitAt(All, "Torrasque", "Anywhere", playerID);
            # (Line 31) trg.Main_Wait(0);
            DoActions(KillUnitAt(All, "Torrasque", "Anywhere", playerID))
            trg.Main_Wait(0)
            # (Line 32) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 33) break;
            EUDBreak()
            # (Line 34) case 3:
        _t5 = EUDSwitchCase()
        # (Line 35) trg.Shape_Square(playerID, 1, "40 + 1n Guardian", 128, 0);
        if _t5(3):
            trg.Shape_Square(playerID, 1, "40 + 1n Guardian", 128, 0)
            # (Line 36) trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 128, 0);
            trg.Shape_Square(playerID, 1, "Protoss Dark Archon", 128, 0)
            # (Line 37) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
            # (Line 38) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
            # (Line 39) Order("40 + 1n Guardian", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 40) trg.Main_Wait(130);
            DoActions(Order("40 + 1n Guardian", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            trg.Main_Wait(130)
            # (Line 41) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 42) break;
            EUDBreak()
            # (Line 43) case 4:
        _t6 = EUDSwitchCase()
        # (Line 44) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 64, 0);
        if _t6(4):
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 64, 0)
            # (Line 45) trg.Shape_Square(playerID, 1, "40 + 1n Mojo", 64, 0);
            trg.Shape_Square(playerID, 1, "40 + 1n Mojo", 64, 0)
            # (Line 46) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 47) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            # (Line 48) Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 49) trg.Main_Wait(130);
            DoActions(Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            trg.Main_Wait(130)
            # (Line 50) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 51) break;
            EUDBreak()
            # (Line 52) case 5:
        _t7 = EUDSwitchCase()
        # (Line 53) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID);
        if _t7(5):
            # (Line 55) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 62, 12);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID))
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 62, 12)
            # (Line 56) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 57) trg.Main_Wait(130);
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            trg.Main_Wait(130)
            # (Line 58) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 59) break;
            EUDBreak()
            # (Line 60) case 6:
        _t8 = EUDSwitchCase()
        # (Line 61) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 60, 25);
        if _t8(6):
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 60, 25)
            # (Line 62) trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 60, 25);
            trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 60, 25)
            # (Line 63) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 64) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            # (Line 65) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 66) trg.Main_Wait(130);
            DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            trg.Main_Wait(130)
            # (Line 67) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 68) break;
            EUDBreak()
            # (Line 69) case 7:
        _t9 = EUDSwitchCase()
        # (Line 70) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
        if _t9(7):
            # (Line 72) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 54, 36);
            DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 54, 36)
            # (Line 73) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 74) trg.Main_Wait(130);
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            trg.Main_Wait(130)
            # (Line 75) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 76) break;
            EUDBreak()
            # (Line 77) case 8:
        _t10 = EUDSwitchCase()
        # (Line 78) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 45, 45);
        if _t10(8):
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 45, 45)
            # (Line 79) trg.Shape_Square(playerID, 1, "40 + 1n Mojo", 45, 45);
            trg.Shape_Square(playerID, 1, "40 + 1n Mojo", 45, 45)
            # (Line 80) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 81) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            # (Line 82) Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 83) trg.Main_Wait(130);
            DoActions(Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            trg.Main_Wait(130)
            # (Line 84) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 85) break;
            EUDBreak()
            # (Line 86) case 9:
        _t11 = EUDSwitchCase()
        # (Line 87) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID);
        if _t11(9):
            # (Line 89) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 36, 54);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID))
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 36, 54)
            # (Line 90) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 91) trg.Main_Wait(130);
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            trg.Main_Wait(130)
            # (Line 92) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 93) break;
            EUDBreak()
            # (Line 94) case 10:
        _t12 = EUDSwitchCase()
        # (Line 95) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 25, 60);
        if _t12(10):
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 25, 60)
            # (Line 96) trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 25, 60);
            trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 25, 60)
            # (Line 97) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 98) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            # (Line 99) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 100) trg.Main_Wait(130);
            DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            trg.Main_Wait(130)
            # (Line 101) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 102) break;
            EUDBreak()
            # (Line 103) case 11:
        _t13 = EUDSwitchCase()
        # (Line 104) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
        if _t13(11):
            # (Line 106) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 12, 60);
            DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 12, 60)
            # (Line 107) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 108) trg.Main_Wait(130);
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            trg.Main_Wait(130)
            # (Line 109) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 110) break;
            EUDBreak()
            # (Line 111) case 12:
        _t14 = EUDSwitchCase()
        # (Line 112) trg.Shape_Square(playerID, 1, "60 + 1n Archon", 25, 60);
        if _t14(12):
            trg.Shape_Square(playerID, 1, "60 + 1n Archon", 25, 60)
            # (Line 113) trg.Shape_Square(playerID, 1, "40 + 1n Mojo", 25, 60);
            trg.Shape_Square(playerID, 1, "40 + 1n Mojo", 25, 60)
            # (Line 114) KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID);
            # (Line 115) MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere");
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", playerID))
            # (Line 116) Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]);
            DoActions(MoveLocation(v.P_LocationID[playerID], v.P_UnitID[playerID], playerID, "Anywhere"))
            # (Line 117) trg.Main_Wait(130);
            DoActions(Order("40 + 1n Mojo", playerID, "Anywhere", Attack, v.P_LocationID[playerID]))
            trg.Main_Wait(130)
            # (Line 118) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 119) break;
            EUDBreak()
            # (Line 120) case 13:
        _t15 = EUDSwitchCase()
        # (Line 121) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID);
        if _t15(13):
            # (Line 122) trg.Main_Wait(200);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", playerID))
            trg.Main_Wait(200)
            # (Line 123) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 124) break;
            EUDBreak()
            # (Line 125) case 14:
        _t16 = EUDSwitchCase()
        # (Line 126) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID);
        if _t16(14):
            # (Line 127) trg.Main_Wait(0);
            DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID))
            trg.Main_Wait(0)
            # (Line 128) v.P_CountMain[playerID] += 1;
            _ARRW(v.P_CountMain, playerID).__iadd__(1)
            # (Line 129) break;
            EUDBreak()
            # (Line 130) case 15:
        _t17 = EUDSwitchCase()
        # (Line 131) trg.SkillEnd();
        if _t17(15):
            trg.SkillEnd()
            # (Line 132) break;
            EUDBreak()
            # (Line 133) }
        # (Line 134) }
        EUDEndSwitch()
        # (Line 135) }
    EUDEndIf()
