## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import Function as f;
import Function as f
# (Line 3) function main(cp)
# (Line 4) {
@EUDFunc
def f_main(cp):
    # (Line 5) if (f.wait[cp] == 0 && f.step[cp] == 0)
    if EUDIf()(EUDSCAnd()(f.wait[cp] == 0)(f.step[cp] == 0)()):
        # (Line 6) {
        # (Line 7) if (Bring(cp, AtLeast, 1, "Protoss Corsair", "[Skill]UseSkill")
        _t2 = EUDIf()
        # (Line 8) && Deaths(CurrentPlayer, AtLeast, 1, " `O Skill Condition")
        # (Line 9) && Deaths(CurrentPlayer, Exactly, 0, " `UniqueCoolTime")
        # (Line 10) && Switch("UiltimateSwitch", Cleared)
        # (Line 11) )
        if _t2(EUDSCAnd()(Bring(cp, AtLeast, 1, "Protoss Corsair", "[Skill]UseSkill"))(Deaths(CurrentPlayer, AtLeast, 1, " `O Skill Condition"))(Deaths(CurrentPlayer, Exactly, 0, " `UniqueCoolTime"))(Switch("UiltimateSwitch", Cleared))()):
            # (Line 12) {
            # (Line 13) f.Voice_Routine(cp, 8);
            f.Voice_Routine(cp, 8)
            # (Line 14) f.step[cp] = 1;
            _ARRW(f.step, cp) << (1)
            # (Line 15) KillUnitAt(1, "Protoss Corsair", "[Skill]UseSkill", cp);
            # (Line 16) }
            DoActions(KillUnitAt(1, "Protoss Corsair", "[Skill]UseSkill", cp))
            # (Line 17) else if (Bring(cp, AtLeast, 1, "Protoss Corsair", "[Skill]UseSkill"))
        if EUDElseIf()(Bring(cp, AtLeast, 1, "Protoss Corsair", "[Skill]UseSkill")):
            # (Line 18) {
            # (Line 19) SetResources(CurrentPlayer, Add, 60, Gas);
            # (Line 20) KillUnitAt(1, "Protoss Corsair", "[Skill]UseSkill", cp);
            DoActions(SetResources(CurrentPlayer, Add, 60, Gas))
            # (Line 21) }
            DoActions(KillUnitAt(1, "Protoss Corsair", "[Skill]UseSkill", cp))
            # (Line 22) else if (Bring(cp, AtLeast, 1, "Protoss Carrier", "[Skill]UseSkill"))
        if EUDElseIf()(Bring(cp, AtLeast, 1, "Protoss Carrier", "[Skill]UseSkill")):
            # (Line 23) {
            # (Line 24) f.step[cp] = 200;
            _ARRW(f.step, cp) << (200)
            # (Line 25) KillUnitAt(1, "Protoss Carrier", "[Skill]UseSkill", cp);
            # (Line 26) }
            DoActions(KillUnitAt(1, "Protoss Carrier", "[Skill]UseSkill", cp))
            # (Line 27) else if (Bring(cp, AtLeast, 1, "Protoss Arbiter", "[Skill]UseSkill"))
        if EUDElseIf()(Bring(cp, AtLeast, 1, "Protoss Arbiter", "[Skill]UseSkill")):
            # (Line 28) {
            # (Line 29) f.step[cp] = 300;
            _ARRW(f.step, cp) << (300)
            # (Line 30) KillUnitAt(1, "Protoss Arbiter", "[Skill]UseSkill", cp);
            # (Line 31) }
            DoActions(KillUnitAt(1, "Protoss Arbiter", "[Skill]UseSkill", cp))
            # (Line 33) else if (Bring(cp, AtLeast, 1, "Protoss Scout", "[Skill]UseSkill"))
        if EUDElseIf()(Bring(cp, AtLeast, 1, "Protoss Scout", "[Skill]UseSkill")):
            # (Line 34) {
            # (Line 35) f.step[cp] = 100;
            _ARRW(f.step, cp) << (100)
            # (Line 36) KillUnitAt(1, "Protoss Scout", "[Skill]UseSkill", cp);
            # (Line 37) }
            DoActions(KillUnitAt(1, "Protoss Scout", "[Skill]UseSkill", cp))
            # (Line 39) }
        EUDEndIf()
        # (Line 42) if (f.wait[cp] >= 2 && f.count[cp] == 0)
    EUDEndIf()
    if EUDIf()(EUDSCAnd()(f.wait[cp] >= 2)(f.count[cp] == 0)()):
        # (Line 43) {
        # (Line 44) if (Bring(cp, AtLeast, 2, "Protoss Scout", "[Skill]UseSkill") && f.step[cp] == 100)
        if EUDIf()(EUDSCAnd()(Bring(cp, AtLeast, 2, "Protoss Scout", "[Skill]UseSkill"))(f.step[cp] == 100)()):
            # (Line 45) {
            # (Line 46) f.Voice_Routine(cp, 1);
            f.Voice_Routine(cp, 1)
            # (Line 47) f.wait[cp] = 0;
            _ARRW(f.wait, cp) << (0)
            # (Line 48) f.count[cp] = 0;
            _ARRW(f.count, cp) << (0)
            # (Line 49) f.loop[cp] = 0;
            _ARRW(f.loop, cp) << (0)
            # (Line 50) f.step[cp] = 110;
            _ARRW(f.step, cp) << (110)
            # (Line 51) KillUnitAt(2, "Protoss Scout", "[Skill]UseSkill", cp);
            # (Line 52) }
            DoActions(KillUnitAt(2, "Protoss Scout", "[Skill]UseSkill", cp))
            # (Line 53) else if (Bring(cp, AtLeast, 1, "Protoss Arbiter", "[Skill]UseSkill")
        _t9 = EUDElseIf()
        # (Line 54) && Bring(cp, AtLeast, 1, "Protoss Carrier", "[Skill]UseSkill")
        # (Line 55) && f.step[cp] == 300)
        if _t9(EUDSCAnd()(Bring(cp, AtLeast, 1, "Protoss Arbiter", "[Skill]UseSkill"))(Bring(cp, AtLeast, 1, "Protoss Carrier", "[Skill]UseSkill"))(f.step[cp] == 300)()):
            # (Line 56) {
            # (Line 57) f.Voice_Routine(cp, 2);
            f.Voice_Routine(cp, 2)
            # (Line 58) f.wait[cp] = 0;
            _ARRW(f.wait, cp) << (0)
            # (Line 59) f.count[cp] = 0;
            _ARRW(f.count, cp) << (0)
            # (Line 60) f.loop[cp] = 0;
            _ARRW(f.loop, cp) << (0)
            # (Line 61) f.step[cp] = 310;
            _ARRW(f.step, cp) << (310)
            # (Line 62) KillUnitAt(1, "Protoss Arbiter", "[Skill]UseSkill", cp);
            # (Line 63) KillUnitAt(1, "Protoss Carrier", "[Skill]UseSkill", cp);
            DoActions(KillUnitAt(1, "Protoss Arbiter", "[Skill]UseSkill", cp))
            # (Line 64) }
            DoActions(KillUnitAt(1, "Protoss Carrier", "[Skill]UseSkill", cp))
            # (Line 65) else if (Bring(cp, AtLeast, 1, "Protoss Carrier", "[Skill]UseSkill")
        _t10 = EUDElseIf()
        # (Line 66) && Bring(cp, AtLeast, 1, "Protoss Arbiter", "[Skill]UseSkill")
        # (Line 67) && f.step[cp] == 200)
        if _t10(EUDSCAnd()(Bring(cp, AtLeast, 1, "Protoss Carrier", "[Skill]UseSkill"))(Bring(cp, AtLeast, 1, "Protoss Arbiter", "[Skill]UseSkill"))(f.step[cp] == 200)()):
            # (Line 68) {
            # (Line 69) f.Voice_Routine(cp, 3);
            f.Voice_Routine(cp, 3)
            # (Line 70) f.wait[cp] = 0;
            _ARRW(f.wait, cp) << (0)
            # (Line 71) f.count[cp] = 0;
            _ARRW(f.count, cp) << (0)
            # (Line 72) f.loop[cp] = 0;
            _ARRW(f.loop, cp) << (0)
            # (Line 73) f.step[cp] = 210;
            _ARRW(f.step, cp) << (210)
            # (Line 74) KillUnitAt(1, "Protoss Carrier", "[Skill]UseSkill", cp);
            # (Line 75) KillUnitAt(1, "Protoss Arbiter", "[Skill]UseSkill", cp);
            DoActions(KillUnitAt(1, "Protoss Carrier", "[Skill]UseSkill", cp))
            # (Line 76) }
            DoActions(KillUnitAt(1, "Protoss Arbiter", "[Skill]UseSkill", cp))
            # (Line 77) else if (Bring(cp, AtLeast, 2, "Protoss Arbiter", "[Skill]UseSkill") && f.step[cp] == 210)
        if EUDElseIf()(EUDSCAnd()(Bring(cp, AtLeast, 2, "Protoss Arbiter", "[Skill]UseSkill"))(f.step[cp] == 210)()):
            # (Line 78) {
            # (Line 79) f.Voice_Routine(cp, 4);
            f.Voice_Routine(cp, 4)
            # (Line 80) f.wait[cp] = 0;
            _ARRW(f.wait, cp) << (0)
            # (Line 81) f.count[cp] = 0;
            _ARRW(f.count, cp) << (0)
            # (Line 82) f.loop[cp] = 0;
            _ARRW(f.loop, cp) << (0)
            # (Line 83) f.step[cp] = 220;
            _ARRW(f.step, cp) << (220)
            # (Line 84) KillUnitAt(2, "Protoss Arbiter", "[Skill]UseSkill", cp);
            # (Line 85) }
            DoActions(KillUnitAt(2, "Protoss Arbiter", "[Skill]UseSkill", cp))
            # (Line 88) else if (Bring(cp, AtLeast, 2, "Protoss Arbiter", "[Skill]UseSkill")
        _t12 = EUDElseIf()
        # (Line 89) && f.step[cp] == 300
        # (Line 90) && Deaths(cp, AtLeast, f.UltimateA[cp], " `UltimateCoolTime"))
        if _t12(EUDSCAnd()(Bring(cp, AtLeast, 2, "Protoss Arbiter", "[Skill]UseSkill"))(f.step[cp] == 300)(Deaths(cp, AtLeast, f.UltimateA[cp], " `UltimateCoolTime"))()):
            # (Line 91) {
            # (Line 92) f.Voice_Routine(cp, 5);
            f.Voice_Routine(cp, 5)
            # (Line 93) f.wait[cp] = 0;
            _ARRW(f.wait, cp) << (0)
            # (Line 94) f.count[cp] = 0;
            _ARRW(f.count, cp) << (0)
            # (Line 95) f.loop[cp] = 0;
            _ARRW(f.loop, cp) << (0)
            # (Line 96) f.step[cp] = 320;
            _ARRW(f.step, cp) << (320)
            # (Line 97) SetDeaths(cp, Subtract, f.UltimateA[cp], " `UltimateCoolTime");
            # (Line 98) KillUnitAt(2, "Protoss Arbiter", "[Skill]UseSkill", cp);
            DoActions(SetDeaths(cp, Subtract, f.UltimateA[cp], " `UltimateCoolTime"))
            # (Line 100) }
            DoActions(KillUnitAt(2, "Protoss Arbiter", "[Skill]UseSkill", cp))
            # (Line 102) }
        EUDEndIf()
        # (Line 103) }
    EUDEndIf()
