## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import Function as f;
import Function as f
# (Line 4) function main(cp)
# (Line 5) {
@EUDFunc
def f_main(cp):
    # (Line 6) if (f.delay[cp] == 0)
    if EUDIf()(f.delay[cp] == 0):
        # (Line 7) {
        # (Line 8) if (f.count[cp] == 0)
        if EUDIf()(f.count[cp] == 0):
            # (Line 9) {
            # (Line 10) if (f.loop[cp] == 0)
            if EUDIf()(f.loop[cp] == 0):
                # (Line 11) {
                # (Line 12) f.SquareShape(cp, 1, "Bengalaas (Jungle)", 50, 0);
                f.SquareShape(cp, 1, "Bengalaas (Jungle)", 50, 0)
                # (Line 13) KillUnitAt(All, "Bengalaas (Jungle)", "Anywhere", cp);
                # (Line 15) f.SquareShape(cp, 1, "40 + 1n Guardian", 50, 50);
                DoActions(KillUnitAt(All, "Bengalaas (Jungle)", "Anywhere", cp))
                f.SquareShape(cp, 1, "40 + 1n Guardian", 50, 50)
                # (Line 16) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", cp);
                # (Line 18) f.SquareShape(cp, 1, "40 + 1n Mojo", 50, 0);
                DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", cp))
                f.SquareShape(cp, 1, "40 + 1n Mojo", 50, 0)
                # (Line 20) MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere");
                # (Line 21) Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]);
                DoActions(MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere"))
                # (Line 22) }
                DoActions(Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]))
                # (Line 23) else if (f.loop[cp] == 2)
            if EUDElseIf()(f.loop[cp] == 2):
                # (Line 24) {
                # (Line 25) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp);
                # (Line 27) f.SquareShape(cp, 1, "Bengalaas (Jungle)", 50, 50);
                DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp))
                f.SquareShape(cp, 1, "Bengalaas (Jungle)", 50, 50)
                # (Line 28) KillUnitAt(All, "Bengalaas (Jungle)", "Anywhere", cp);
                # (Line 30) f.SquareShape(cp, 1, "Kakaru (Twilight)", 100, 100);
                DoActions(KillUnitAt(All, "Bengalaas (Jungle)", "Anywhere", cp))
                f.SquareShape(cp, 1, "Kakaru (Twilight)", 100, 100)
                # (Line 31) KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", cp);
                # (Line 33) f.SquareShape(cp, 1, "40 + 1n Mojo", 50, 50);
                DoActions(KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", cp))
                f.SquareShape(cp, 1, "40 + 1n Mojo", 50, 50)
                # (Line 35) MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere");
                # (Line 36) Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]);
                DoActions(MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere"))
                # (Line 37) }
                DoActions(Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]))
                # (Line 38) else if (f.loop[cp] == 4)
            if EUDElseIf()(f.loop[cp] == 4):
                # (Line 39) {
                # (Line 40) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp);
                # (Line 42) f.DotShape(cp, 1, "Target", 0, 0);
                DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp))
                f.DotShape(cp, 1, "Target", 0, 0)
                # (Line 43) KillUnitAt(All, "Target", "Anywhere", cp);
                # (Line 46) f.SquareShape(cp, 1, "40 + 1n Mutalisk", 50, 50);
                DoActions(KillUnitAt(All, "Target", "Anywhere", cp))
                f.SquareShape(cp, 1, "40 + 1n Mutalisk", 50, 50)
                # (Line 47) KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", cp);
                # (Line 49) f.SquareShape(cp, 1, "50 + 1n Battlecruiser", 100, 100);
                DoActions(KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", cp))
                f.SquareShape(cp, 1, "50 + 1n Battlecruiser", 100, 100)
                # (Line 50) KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", cp);
                # (Line 52) f.SquareShape(cp, 1, "40 + 1n Mojo", 100, 0);
                DoActions(KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", cp))
                f.SquareShape(cp, 1, "40 + 1n Mojo", 100, 0)
                # (Line 54) MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere");
                # (Line 55) Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]);
                DoActions(MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere"))
                # (Line 56) }
                DoActions(Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]))
                # (Line 57) else if (f.loop[cp] == 6)
            if EUDElseIf()(f.loop[cp] == 6):
                # (Line 58) {
                # (Line 59) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp);
                # (Line 61) f.DotShape(cp, 1, "Target", 0, 0);
                DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp))
                f.DotShape(cp, 1, "Target", 0, 0)
                # (Line 62) KillUnitAt(All, "Target", "Anywhere", cp);
                # (Line 64) f.SquareShape(cp, 1, "40 + 1n Mutalisk", 50, 50);
                DoActions(KillUnitAt(All, "Target", "Anywhere", cp))
                f.SquareShape(cp, 1, "40 + 1n Mutalisk", 50, 50)
                # (Line 65) KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", cp);
                # (Line 67) f.SquareShape(cp, 1, "50 + 1n Battlecruiser", 100, 0);
                DoActions(KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", cp))
                f.SquareShape(cp, 1, "50 + 1n Battlecruiser", 100, 0)
                # (Line 68) KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", cp);
                # (Line 70) f.SquareShape(cp, 1, "40 + 1n Mojo", 50, 0);
                DoActions(KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", cp))
                f.SquareShape(cp, 1, "40 + 1n Mojo", 50, 0)
                # (Line 72) MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere");
                # (Line 73) Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]);
                DoActions(MoveLocation(f.location[cp], f.heroID[cp], cp, "Anywhere"))
                # (Line 74) }
                DoActions(Order("40 + 1n Mojo", cp, "Anywhere", Attack, f.location[cp]))
                # (Line 76) f.SkillWait(cp, 80);
            EUDEndIf()
            f.SkillWait(cp, 80)
            # (Line 78) f.loop[cp] += 1;
            _ARRW(f.loop, cp).__iadd__(1)
            # (Line 80) if (f.loop[cp] == 8)
            if EUDIf()(f.loop[cp] == 8):
                # (Line 81) {
                # (Line 82) f.count[cp] += 1;
                _ARRW(f.count, cp).__iadd__(1)
                # (Line 83) f.loop[cp] = 0;
                _ARRW(f.loop, cp) << (0)
                # (Line 84) }
                # (Line 85) }
            EUDEndIf()
            # (Line 86) else if (f.count[cp] == 1)
        if EUDElseIf()(f.count[cp] == 1):
            # (Line 87) {
            # (Line 88) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp);
            # (Line 90) f.SkillEnd(cp);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", cp))
            f.SkillEnd(cp)
            # (Line 91) }
            # (Line 92) }
        EUDEndIf()
        # (Line 93) }
    EUDEndIf()
