## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import variable as v;
import variable as v
# (Line 3) import func.trig as trg;
from func import trig as trg
# (Line 5) function main(playerID)
# (Line 6) {
@EUDFunc
def f_main(playerID):
    # (Line 7) if (v.P_WaitMain[playerID] == 0)
    if EUDIf()(v.P_WaitMain[playerID] == 0):
        # (Line 8) {
        # (Line 9) if (v.P_CountMain[playerID] == 0)
        if EUDIf()(v.P_CountMain[playerID] == 0):
            # (Line 10) {
            # (Line 11) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 12) {
                # (Line 13) trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 3, 50);
                trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 3, 50)
                # (Line 14) trg.Shape_NxNSquare(playerID, 1, "Protoss Dark Archon", 3, 50);
                trg.Shape_NxNSquare(playerID, 1, "Protoss Dark Archon", 3, 50)
                # (Line 15) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID);
                # (Line 16) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID))
                # (Line 17) }
                DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
                # (Line 18) else if (v.P_LoopMain[playerID] == 2)
            if EUDElseIf()(v.P_LoopMain[playerID] == 2):
                # (Line 19) {
                # (Line 20) trg.Shape_Edge(playerID, 1, "40 + 1n Guardian", 45, 5, 100);
                trg.Shape_Edge(playerID, 1, "40 + 1n Guardian", 45, 5, 100)
                # (Line 21) trg.Shape_Edge(playerID, 1, "Protoss Dark Archon", 45, 5, 100);
                trg.Shape_Edge(playerID, 1, "Protoss Dark Archon", 45, 5, 100)
                # (Line 22) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID);
                # (Line 23) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID))
                # (Line 24) }
                DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
                # (Line 25) else if (v.P_LoopMain[playerID] == 4)
            if EUDElseIf()(v.P_LoopMain[playerID] == 4):
                # (Line 26) {
                # (Line 27) trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 50, 50);
                trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 50, 50)
                # (Line 28) trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 50, 50);
                trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 50, 50)
                # (Line 29) trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50);
                trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50)
                # (Line 31) KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID);
                # (Line 32) KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID))
                # (Line 34) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere");
                DoActions(KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID))
                # (Line 35) }
                DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere"))
                # (Line 36) else if (v.P_LoopMain[playerID] == 6)
            if EUDElseIf()(v.P_LoopMain[playerID] == 6):
                # (Line 37) {
                # (Line 38) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
                # (Line 40) trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 0, 50);
                DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 0, 50)
                # (Line 41) trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 0, 50);
                trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 0, 50)
                # (Line 42) trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50);
                trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50)
                # (Line 44) KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID);
                # (Line 45) KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID))
                # (Line 47) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere");
                DoActions(KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID))
                # (Line 48) }
                DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere"))
                # (Line 49) else if (v.P_LoopMain[playerID] == 8)
            if EUDElseIf()(v.P_LoopMain[playerID] == 8):
                # (Line 50) {
                # (Line 51) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
                # (Line 53) trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 50, 50);
                DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 50, 50)
                # (Line 54) trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 50, 50);
                trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 50, 50)
                # (Line 55) trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50);
                trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50)
                # (Line 57) KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID);
                # (Line 58) KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID))
                # (Line 60) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere");
                DoActions(KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID))
                # (Line 61) }
                DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere"))
                # (Line 62) else if (v.P_LoopMain[playerID] == 10)
            if EUDElseIf()(v.P_LoopMain[playerID] == 10):
                # (Line 63) {
                # (Line 64) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
                # (Line 66) trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 0, 50);
                DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
                trg.Shape_Square(playerID, 1, "40 + 1n Wraith", 0, 50)
                # (Line 67) trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 0, 50);
                trg.Shape_Square(playerID, 1, "40 + 1n Goliath", 0, 50)
                # (Line 68) trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50);
                trg.Shape_Square(playerID, 1, "Kakaru (Twilight)", 0, 50)
                # (Line 70) KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID);
                # (Line 71) KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "40 + 1n Goliath", "Anywhere", playerID))
                # (Line 73) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere");
                DoActions(KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID))
                # (Line 74) }
                DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere"))
                # (Line 76) if ((v.P_LoopMain[playerID] % 8) / 4 == 0)
            EUDEndIf()
            if EUDIf()((v.P_LoopMain[playerID] % 8) // 4 == 0):
                # (Line 77) {
                # (Line 78) trg.Shape_Double(playerID, 1, "Rhynadon (Badlands)", 100 - 50 * (v.P_LoopMain[playerID] % 4), 100);
                trg.Shape_Double(playerID, 1, "Rhynadon (Badlands)", 100 - 50 * (v.P_LoopMain[playerID] % 4), 100)
                # (Line 79) KillUnitAt(All, "Rhynadon (Badlands)", "Anywhere", playerID);
                # (Line 80) }
                DoActions(KillUnitAt(All, "Rhynadon (Badlands)", "Anywhere", playerID))
                # (Line 81) else if ((v.P_LoopMain[playerID] % 8) / 4 == 1)
            if EUDElseIf()((v.P_LoopMain[playerID] % 8) // 4 == 1):
                # (Line 82) {
                # (Line 83) trg.Shape_Double(playerID, 1, "Rhynadon (Badlands)", -100, 100 - 50 * (v.P_LoopMain[playerID] % 4));
                trg.Shape_Double(playerID, 1, "Rhynadon (Badlands)", -100, 100 - 50 * (v.P_LoopMain[playerID] % 4))
                # (Line 84) KillUnitAt(All, "Rhynadon (Badlands)", "Anywhere", playerID);
                # (Line 85) }
                DoActions(KillUnitAt(All, "Rhynadon (Badlands)", "Anywhere", playerID))
                # (Line 87) trg.Main_Wait(80);
            EUDEndIf()
            trg.Main_Wait(80)
            # (Line 89) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 91) if (v.P_LoopMain[playerID] == 12)
            if EUDIf()(v.P_LoopMain[playerID] == 12):
                # (Line 92) {
                # (Line 93) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
                # (Line 95) v.P_CountMain[playerID] += 1;
                DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 96) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 97) }
                # (Line 98) }
            EUDEndIf()
            # (Line 99) else if (v.P_CountMain[playerID] == 1)
        if EUDElseIf()(v.P_CountMain[playerID] == 1):
            # (Line 100) {
            # (Line 101) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 102) {
                # (Line 103) trg.Shape_NxNSquare(playerID, 1, "Protoss Dark Archon", 3, 50);
                trg.Shape_NxNSquare(playerID, 1, "Protoss Dark Archon", 3, 50)
                # (Line 104) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
                # (Line 105) }
                DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
                # (Line 106) else if (v.P_LoopMain[playerID] == 2)
            if EUDElseIf()(v.P_LoopMain[playerID] == 2):
                # (Line 107) {
                # (Line 108) trg.Shape_Edge(playerID, 1, "Protoss Dark Archon", 45, 5, 100);
                trg.Shape_Edge(playerID, 1, "Protoss Dark Archon", 45, 5, 100)
                # (Line 109) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
                # (Line 110) }
                DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
                # (Line 111) else if (v.P_LoopMain[playerID] == 4)
            if EUDElseIf()(v.P_LoopMain[playerID] == 4):
                # (Line 112) {
                # (Line 113) trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 3, 50);
                trg.Shape_NxNSquare(playerID, 1, "40 + 1n Guardian", 3, 50)
                # (Line 114) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID);
                # (Line 115) }
                DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID))
                # (Line 116) else if (v.P_LoopMain[playerID] == 6)
            if EUDElseIf()(v.P_LoopMain[playerID] == 6):
                # (Line 117) {
                # (Line 118) trg.Shape_NxNSquare(playerID, 1, "40 + 1n Wraith", 3, 50);
                trg.Shape_NxNSquare(playerID, 1, "40 + 1n Wraith", 3, 50)
                # (Line 120) Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere");
                # (Line 121) }
                DoActions(Order("40 + 1n Wraith", playerID, "Anywhere", Attack, "Anywhere"))
                # (Line 123) trg.Main_Wait(80);
            EUDEndIf()
            trg.Main_Wait(80)
            # (Line 125) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 127) if (v.P_LoopMain[playerID] == 8)
            if EUDIf()(v.P_LoopMain[playerID] == 8):
                # (Line 128) {
                # (Line 129) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 130) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 131) }
                # (Line 132) }
            EUDEndIf()
            # (Line 133) else if (v.P_CountMain[playerID] == 2)
        if EUDElseIf()(v.P_CountMain[playerID] == 2):
            # (Line 134) {
            # (Line 135) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID);
            # (Line 137) trg.SkillEnd();
            DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", playerID))
            trg.SkillEnd()
            # (Line 138) }
            # (Line 139) }
        EUDEndIf()
        # (Line 140) }
    EUDEndIf()
