## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import variable as v;
import variable as v
# (Line 3) import func.trig as trg;
from func import trig as trg
# (Line 4) import func.sound as s;
from func import sound as s
# (Line 6) const P_player		= PVariable();
P_player = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 7) const P_observer 	= PVariable();
P_observer = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 9) function Text(num);
# (Line 11) function player(playerID)
# (Line 12) {
@EUDFunc
def f_player(playerID):
    # (Line 13) Text(P_player[playerID]);
    Text(P_player[playerID])
    # (Line 14) P_player[playerID] = 0;
    _ARRW(P_player, playerID) << (0)
    # (Line 15) }
    # (Line 17) function observer(playerID)

# (Line 18) {
@EUDFunc
def f_observer(playerID):
    # (Line 19) Text(P_observer[playerID - 128]);
    Text(P_observer[playerID - 128])
    # (Line 20) P_observer[playerID - 128] = 0;
    _ARRW(P_observer, playerID - 128) << (0)
    # (Line 21) }
    # (Line 23) function main(playerID)

# (Line 24) {
@EUDFunc
def f_main(playerID):
    # (Line 25) if (playerID < 6) 	{ player(playerID); 	}
    if EUDIf()(playerID >= 6, neg=True):
        f_player(playerID)
        # (Line 26) else  			{ observer(playerID); }
    if EUDElse()():
        f_observer(playerID)
        # (Line 27) }
    EUDEndIf()
    # (Line 29) function Text(num)

# (Line 30) {
@EUDFunc
def Text(num):
    # (Line 31) switch (num)
    EUDSwitch(num)
    # (Line 32) {
    # (Line 33) case 1:
    _t1 = EUDSwitchCase()
    # (Line 34) PlayWAV("Yume_Unique.ogg");
    if _t1(1):
        # (Line 35) v.stb.print("\x13\x1BTsubakuro Yume\n");
        DoActions(PlayWAV("Yume_Unique.ogg"))
        v.stb.print("\x13\x1BTsubakuro Yume\n")
        # (Line 36) v.stb.print("\x13\x04시간이 없으니까 이제... 끝낼게!\x04\n");
        v.stb.print("\x13\x04시간이 없으니까 이제... 끝낼게!\x04\n")
        # (Line 37) break;
        EUDBreak()
        # (Line 38) case 2:
    _t2 = EUDSwitchCase()
    # (Line 39) PlayWAV("Yume_01.ogg");
    if _t2(2):
        # (Line 40) v.stb.print("\x13\x1BTsubakuro Yume\n");
        DoActions(PlayWAV("Yume_01.ogg"))
        v.stb.print("\x13\x1BTsubakuro Yume\n")
        # (Line 41) v.stb.print("\x13\x04그렇게 나와야지, 그렇지 않으면 내가 굉장하다는 걸 보여줄 수 없잖아\x04\n");
        v.stb.print("\x13\x04그렇게 나와야지, 그렇지 않으면 내가 굉장하다는 걸 보여줄 수 없잖아\x04\n")
        # (Line 42) break;
        EUDBreak()
        # (Line 43) case 3:
    _t3 = EUDSwitchCase()
    # (Line 44) PlayWAV("Yume_02.ogg");
    if _t3(3):
        # (Line 45) v.stb.print("\x13\x1BTsubakuro Yume\n");
        DoActions(PlayWAV("Yume_02.ogg"))
        v.stb.print("\x13\x1BTsubakuro Yume\n")
        # (Line 46) v.stb.print("\x13\x04벌써 끝이야? 아직 아직, 이제부터지!\x04\n");
        v.stb.print("\x13\x04벌써 끝이야? 아직 아직, 이제부터지!\x04\n")
        # (Line 47) break;
        EUDBreak()
        # (Line 48) case 4:
    _t4 = EUDSwitchCase()
    # (Line 49) PlayWAV("Yume_03.ogg");
    if _t4(4):
        # (Line 50) v.stb.print("\x13\x1BTsubakuro Yume\n");
        DoActions(PlayWAV("Yume_03.ogg"))
        v.stb.print("\x13\x1BTsubakuro Yume\n")
        # (Line 51) v.stb.print("\x13\x04어이쿠~ 라거나!\x04\n");
        v.stb.print("\x13\x04어이쿠~ 라거나!\x04\n")
        # (Line 52) break;
        EUDBreak()
        # (Line 53) case 5:
    _t5 = EUDSwitchCase()
    # (Line 54) PlayWAV("Yume_Ult.ogg");
    if _t5(5):
        # (Line 55) break;
        DoActions(PlayWAV("Yume_Ult.ogg"))
        EUDBreak()
        # (Line 56) case 6:
    _t6 = EUDSwitchCase()
    # (Line 57) v.stb.print("\x13\x1BTsubakuro Yume\n");
    if _t6(6):
        v.stb.print("\x13\x1BTsubakuro Yume\n")
        # (Line 58) v.stb.print("\x13\x04아아~ 쓸 데 없는 시간 써버렸다\x04\n");
        v.stb.print("\x13\x04아아~ 쓸 데 없는 시간 써버렸다\x04\n")
        # (Line 59) break;
        EUDBreak()
        # (Line 60) case 7:
    _t7 = EUDSwitchCase()
    # (Line 61) PlayWAV("Yume_04.ogg");
    if _t7(7):
        # (Line 62) v.stb.print("\x13\x1BTsubakuro Yume\n");
        DoActions(PlayWAV("Yume_04.ogg"))
        v.stb.print("\x13\x1BTsubakuro Yume\n")
        # (Line 63) v.stb.print("\x13\x04닛카리 아오에\x04\n");
        v.stb.print("\x13\x04닛카리 아오에\x04\n")
        # (Line 64) break;
        EUDBreak()
        # (Line 65) case 8:
    _t8 = EUDSwitchCase()
    # (Line 66) PlayWAV("Yume_05.ogg");
    if _t8(8):
        # (Line 67) break;
        DoActions(PlayWAV("Yume_05.ogg"))
        EUDBreak()
        # (Line 68) }
    # (Line 69) }
    EUDEndSwitch()
