## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import variable as v;
import variable as v
# (Line 2) import func.trig as trg;
from func import trig as trg
# (Line 3) import func.sound as s;
from func import sound as s
# (Line 5) const P_player		= PVariable();
P_player = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 6) const P_observer 	= PVariable();
P_observer = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 7) const P_type 		= PVariable();
P_type = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 9) function Text1(num);
# (Line 10) function Text2(num);
# (Line 11) function Text3(num);
# (Line 13) function player(playerID)
# (Line 14) {
@EUDFunc
def f_player(playerID):
    # (Line 15) if (P_type[playerID] == 1) { Text1(P_player[playerID]); }
    if EUDIf()(P_type[playerID] == 1):
        Text1(P_player[playerID])
        # (Line 16) if (P_type[playerID] == 2) { Text2(P_player[playerID]); }
    EUDEndIf()
    if EUDIf()(P_type[playerID] == 2):
        Text2(P_player[playerID])
        # (Line 17) if (P_type[playerID] == 3) { Text3(P_player[playerID]); }
    EUDEndIf()
    if EUDIf()(P_type[playerID] == 3):
        Text3(P_player[playerID])
        # (Line 18) P_player[playerID] = 0;
    EUDEndIf()
    _ARRW(P_player, playerID) << (0)
    # (Line 19) }
    # (Line 21) function observer(playerID)

# (Line 22) {
@EUDFunc
def f_observer(playerID):
    # (Line 23) if (P_type[playerID] == 1) { Text1(P_observer[playerID - 128]); }
    if EUDIf()(P_type[playerID] == 1):
        Text1(P_observer[playerID - 128])
        # (Line 24) if (P_type[playerID] == 2) { Text2(P_observer[playerID - 128]); }
    EUDEndIf()
    if EUDIf()(P_type[playerID] == 2):
        Text2(P_observer[playerID - 128])
        # (Line 25) if (P_type[playerID] == 3) { Text3(P_observer[playerID - 128]); }
    EUDEndIf()
    if EUDIf()(P_type[playerID] == 3):
        Text3(P_observer[playerID - 128])
        # (Line 26) P_observer[playerID - 128] = 0;
    EUDEndIf()
    _ARRW(P_observer, playerID - 128) << (0)
    # (Line 27) }
    # (Line 29) function main(playerID)

# (Line 30) {
@EUDFunc
def f_main(playerID):
    # (Line 31) if (playerID < 6) 	{ player(playerID); 	}
    if EUDIf()(playerID >= 6, neg=True):
        f_player(playerID)
        # (Line 32) else  			{ observer(playerID); }
    if EUDElse()():
        f_observer(playerID)
        # (Line 33) }
    EUDEndIf()
    # (Line 38) function Text1(num)

# (Line 39) {
@EUDFunc
def Text1(num):
    # (Line 40) switch (num)
    EUDSwitch(num)
    # (Line 41) {
    # (Line 42) case 1000:
    _t1 = EUDSwitchCase()
    # (Line 43) PlayWAV("Cecillia_01.ogg");
    if _t1(1000):
        # (Line 44) v.stb.print("\n\x13\x17Cecillia\n\x13\x04「　간다, \x17파동각!　\x04」\n");
        DoActions(PlayWAV("Cecillia_01.ogg"))
        v.stb.print("\n\x13\x17Cecillia\n\x13\x04「　간다, \x17파동각!　\x04」\n")
        # (Line 46) break;
        EUDBreak()
        # (Line 47) case 1010:
    _t2 = EUDSwitchCase()
    # (Line 48) PlayWAV("Cecillia_02.ogg");
    if _t2(1010):
        # (Line 49) v.stb.print("\n\x13\x17Cecillia\n\x13\x04「　받아라! \x17천추각!　\x04」\n");
        DoActions(PlayWAV("Cecillia_02.ogg"))
        v.stb.print("\n\x13\x17Cecillia\n\x13\x04「　받아라! \x17천추각!　\x04」\n")
        # (Line 51) break;
        EUDBreak()
        # (Line 52) case 1020:
    _t3 = EUDSwitchCase()
    # (Line 53) PlayWAV("Cecillia_03.ogg");
    if _t3(1020):
        # (Line 54) v.stb.print("\n\x13\x17Cecillia\n\x13\x04「　부셔져라, \x06폭렬각!!!　\x04」\n");
        DoActions(PlayWAV("Cecillia_03.ogg"))
        v.stb.print("\n\x13\x17Cecillia\n\x13\x04「　부셔져라, \x06폭렬각!!!　\x04」\n")
        # (Line 56) break;
        EUDBreak()
        # (Line 57) }
    # (Line 58) }
    EUDEndSwitch()
    # (Line 60) function Text2(num)

# (Line 61) {
@EUDFunc
def Text2(num):
    # (Line 62) switch (num)
    EUDSwitch(num)
    # (Line 63) {
    # (Line 64) case 7000:
    _t1 = EUDSwitchCase()
    # (Line 65) PlayWAV("Cecillia_Uiltimate.ogg");
    if _t1(7000):
        # (Line 66) v.stb.printAt(3,"\x13\x17Cecillia\n\n\x13\x04「　하아앗.. \x06필살 유성각!　\x04」");
        DoActions(PlayWAV("Cecillia_Uiltimate.ogg"))
        v.stb.printAt(3, "\x13\x17Cecillia\n\n\x13\x04「　하아앗.. \x06필살 유성각!　\x04」")
        # (Line 68) break;
        EUDBreak()
        # (Line 69) }
    # (Line 70) }
    EUDEndSwitch()
    # (Line 72) function Text3(num)

# (Line 73) {
@EUDFunc
def Text3(num):
    # (Line 74) switch (num)
    EUDSwitch(num)
    # (Line 75) {
    # (Line 76) case 7000:
    _t1 = EUDSwitchCase()
    # (Line 77) PlayWAV("Cecillia_Unique.ogg");
    if _t1(7000):
        # (Line 78) v.stb.printAt(3,"\x13\x17Cecillia\n\x13\x04「　괴로워도 포기하면 거기서 끝이라고? 용기란 포기하지 않는 걸 말하는거라고　\x04」");
        DoActions(PlayWAV("Cecillia_Unique.ogg"))
        v.stb.printAt(3, "\x13\x17Cecillia\n\x13\x04「　괴로워도 포기하면 거기서 끝이라고? 용기란 포기하지 않는 걸 말하는거라고　\x04」")
        # (Line 80) break;
        EUDBreak()
        # (Line 81) }
    # (Line 82) }
    EUDEndSwitch()
