## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _RELIMP(path, mod_name):
    import inspect, pathlib, importlib.util
    p = pathlib.Path(inspect.getabsfile(inspect.currentframe())).parent
    for s in path.split("."):
        if s == "":  p = p.parent
        else:  p = p / s
    try:
        spec = importlib.util.spec_from_file_location(mod_name, p / (mod_name + ".py"))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    except FileNotFoundError:
        loader = EPSLoader(mod_name, str(p / (mod_name + ".eps")))
        spec = importlib.util.spec_from_loader(mod_name, loader)
        module = loader.create_module(spec)
        loader.exec_module(module)
    return module

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import variable as v;
import variable as v
# (Line 3) import func.trig as trg;
from func import trig as trg
# (Line 4) import func.sound as s;
from func import sound as s
# (Line 6) function main(playerID)
# (Line 7) {
@EUDFunc
def f_main(playerID):
    # (Line 8) MoveLocation("27.Magane_Bozo", v.P_UnitID[playerID], playerID, "Anywhere");
    # (Line 10) if (v.P_WaitMain[playerID] == 0)
    DoActions(MoveLocation("27.Magane_Bozo", v.P_UnitID[playerID], playerID, "Anywhere"))
    if EUDIf()(v.P_WaitMain[playerID] == 0):
        # (Line 11) {
        # (Line 12) if (v.P_CountMain[playerID] == 0)
        if EUDIf()(v.P_CountMain[playerID] == 0):
            # (Line 13) {
            # (Line 14) if (v.P_LoopMain[playerID] == 0)
            if EUDIf()(v.P_LoopMain[playerID] == 0):
                # (Line 15) {
                # (Line 16) trg.Shape_Edge(playerID, 1, "40 + 1n Guardian", 45, 3, 50);
                trg.Shape_Edge(playerID, 1, "40 + 1n Guardian", 45, 3, 50)
                # (Line 17) trg.Shape_Edge(playerID, 1, "Protoss Dark Archon", 45, 3, 50);
                trg.Shape_Edge(playerID, 1, "Protoss Dark Archon", 45, 3, 50)
                # (Line 18) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID);
                # (Line 19) KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", playerID))
                # (Line 20) }
                DoActions(KillUnitAt(All, "Protoss Dark Archon", "Anywhere", playerID))
                # (Line 21) else if (v.P_LoopMain[playerID] == 2)
            if EUDElseIf()(v.P_LoopMain[playerID] == 2):
                # (Line 22) {
                # (Line 23) trg.Shape_Edge(playerID, 1, "Kakaru (Twilight)", 45, 3, 50);
                trg.Shape_Edge(playerID, 1, "Kakaru (Twilight)", 45, 3, 50)
                # (Line 24) trg.Shape_Edge(playerID, 1, " Unit. Hoffnung 25000", 45, 3, 50);
                trg.Shape_Edge(playerID, 1, " Unit. Hoffnung 25000", 45, 3, 50)
                # (Line 25) KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID);
                # (Line 26) KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID);
                DoActions(KillUnitAt(All, "Kakaru (Twilight)", "Anywhere", playerID))
                # (Line 27) }
                DoActions(KillUnitAt(All, " Unit. Hoffnung 25000", "Anywhere", playerID))
                # (Line 29) trg.Main_Wait(80);
            EUDEndIf()
            trg.Main_Wait(80)
            # (Line 31) v.P_LoopMain[playerID] += 1;
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 33) if (v.P_LoopMain[playerID] == 16)
            if EUDIf()(v.P_LoopMain[playerID] == 16):
                # (Line 34) {
                # (Line 35) s.CharacterVoice(9);
                s.CharacterVoice(9)
                # (Line 36) SetSwitch("Recall - Magane", Set);
                # (Line 38) v.P_CountMain[playerID] += 1;
                DoActions(SetSwitch("Recall - Magane", Set))
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 39) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 40) }
                # (Line 41) }
            EUDEndIf()
            # (Line 42) else if (v.P_CountMain[playerID] == 1)
        if EUDElseIf()(v.P_CountMain[playerID] == 1):
            # (Line 43) {
            # (Line 44) if (Switch("UiltimateSwitch", Cleared))
            if EUDIf()(Switch("UiltimateSwitch", Cleared)):
                # (Line 45) {
                # (Line 46) if (playerID < 3)
                if EUDIf()(playerID >= 3, neg=True):
                    # (Line 47) {
                    # (Line 48) GiveUnits(All, "Protoss Dark Templar", Foes, "27.Magane_Bozo", P7);
                    # (Line 49) GiveUnits(All, "40 + 1n Marine", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "Protoss Dark Templar", Foes, "27.Magane_Bozo", P7))
                    # (Line 50) GiveUnits(All, "40 + 1n Ghost", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Marine", Foes, "27.Magane_Bozo", P7))
                    # (Line 51) GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Ghost", Foes, "27.Magane_Bozo", P7))
                    # (Line 52) GiveUnits(All, "40 + 1n Goliath", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P7))
                    # (Line 53) GiveUnits(All, "40 + 1n Wraith", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Goliath", Foes, "27.Magane_Bozo", P7))
                    # (Line 54) GiveUnits(All, "40 + 1n Firebat", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Wraith", Foes, "27.Magane_Bozo", P7))
                    # (Line 55) GiveUnits(All, "40 + 1n Zergling", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Firebat", Foes, "27.Magane_Bozo", P7))
                    # (Line 56) GiveUnits(All, " Creep. Licht", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Zergling", Foes, "27.Magane_Bozo", P7))
                    # (Line 57) GiveUnits(All, "40 + 1n Drone", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, " Creep. Licht", Foes, "27.Magane_Bozo", P7))
                    # (Line 58) GiveUnits(All, "40 + 1n Mutalisk", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Drone", Foes, "27.Magane_Bozo", P7))
                    # (Line 59) GiveUnits(All, "40 + 1n Guardian", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Mutalisk", Foes, "27.Magane_Bozo", P7))
                    # (Line 60) GiveUnits(All, "40 + 1n Zealot", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Guardian", Foes, "27.Magane_Bozo", P7))
                    # (Line 61) GiveUnits(All, "40 + 3n Zeratul", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Zealot", Foes, "27.Magane_Bozo", P7))
                    # (Line 62) GiveUnits(All, "40 + 1n Mojo", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 3n Zeratul", Foes, "27.Magane_Bozo", P7))
                    # (Line 63) GiveUnits(All, "40 + 1n Gantrithor", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Mojo", Foes, "27.Magane_Bozo", P7))
                    # (Line 64) GiveUnits(All, "40 + 1n Lurker", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Gantrithor", Foes, "27.Magane_Bozo", P7))
                    # (Line 65) GiveUnits(All, "50 + 1n Tank", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "40 + 1n Lurker", Foes, "27.Magane_Bozo", P7))
                    # (Line 66) GiveUnits(All, "50 + 1n Battlecruiser", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "50 + 1n Tank", Foes, "27.Magane_Bozo", P7))
                    # (Line 67) GiveUnits(All, "60 + 3n Siege", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "50 + 1n Battlecruiser", Foes, "27.Magane_Bozo", P7))
                    # (Line 68) GiveUnits(All, "60 + 1n Siege", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 3n Siege", Foes, "27.Magane_Bozo", P7))
                    # (Line 69) GiveUnits(All, "60 + 1n Hydralisk", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 1n Siege", Foes, "27.Magane_Bozo", P7))
                    # (Line 70) GiveUnits(All, "60 + 1n Dragoon", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 1n Hydralisk", Foes, "27.Magane_Bozo", P7))
                    # (Line 71) GiveUnits(All, "60 + 1n High Templar", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 1n Dragoon", Foes, "27.Magane_Bozo", P7))
                    # (Line 72) GiveUnits(All, "60 + 1n Archon", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 1n High Templar", Foes, "27.Magane_Bozo", P7))
                    # (Line 73) GiveUnits(All, "60 + 1n Danimoth", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 1n Archon", Foes, "27.Magane_Bozo", P7))
                    # (Line 74) GiveUnits(All, "60 + 3n Ghost", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 1n Danimoth", Foes, "27.Magane_Bozo", P7))
                    # (Line 75) GiveUnits(All, "80 + 1n Goliath", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "60 + 3n Ghost", Foes, "27.Magane_Bozo", P7))
                    # (Line 76) GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Goliath", Foes, "27.Magane_Bozo", P7))
                    # (Line 77) GiveUnits(All, "80 + 1n Marine", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P7))
                    # (Line 78) GiveUnits(All, "80 + 1n Tom Kazansky", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Marine", Foes, "27.Magane_Bozo", P7))
                    # (Line 79) GiveUnits(All, "80 + 1n Tank", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Tom Kazansky", Foes, "27.Magane_Bozo", P7))
                    # (Line 80) GiveUnits(All, "80 + 1n Mutalisk", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Tank", Foes, "27.Magane_Bozo", P7))
                    # (Line 81) GiveUnits(All, "80 + 1n Guardian", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Mutalisk", Foes, "27.Magane_Bozo", P7))
                    # (Line 82) GiveUnits(All, "80 + 1n Artanis", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Guardian", Foes, "27.Magane_Bozo", P7))
                    # (Line 83) GiveUnits(All, "80 + 1n Ghost", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Artanis", Foes, "27.Magane_Bozo", P7))
                    # (Line 84) GiveUnits(All, "100 + 1n Hyperion", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "80 + 1n Ghost", Foes, "27.Magane_Bozo", P7))
                    # (Line 85) GiveUnits(All, "100 + 1n Dragoon", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "100 + 1n Hyperion", Foes, "27.Magane_Bozo", P7))
                    # (Line 86) GiveUnits(All, "120 + 1n Archon", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "100 + 1n Dragoon", Foes, "27.Magane_Bozo", P7))
                    # (Line 87) GiveUnits(All, "130 + 1n Norad", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "120 + 1n Archon", Foes, "27.Magane_Bozo", P7))
                    # (Line 88) GiveUnits(All, "130 + 1n Arbiter", Foes, "27.Magane_Bozo", P7);
                    DoActions(GiveUnits(All, "130 + 1n Norad", Foes, "27.Magane_Bozo", P7))
                    # (Line 89) }
                    DoActions(GiveUnits(All, "130 + 1n Arbiter", Foes, "27.Magane_Bozo", P7))
                    # (Line 90) if (playerID >= 3)
                EUDEndIf()
                if EUDIf()(playerID >= 3):
                    # (Line 91) {
                    # (Line 92) GiveUnits(All, "Protoss Dark Templar", Foes, "27.Magane_Bozo", P8);
                    # (Line 93) GiveUnits(All, "40 + 1n Marine", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "Protoss Dark Templar", Foes, "27.Magane_Bozo", P8))
                    # (Line 94) GiveUnits(All, "40 + 1n Ghost", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Marine", Foes, "27.Magane_Bozo", P8))
                    # (Line 95) GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Ghost", Foes, "27.Magane_Bozo", P8))
                    # (Line 96) GiveUnits(All, "40 + 1n Goliath", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P8))
                    # (Line 97) GiveUnits(All, "40 + 1n Wraith", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Goliath", Foes, "27.Magane_Bozo", P8))
                    # (Line 98) GiveUnits(All, "40 + 1n Firebat", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Wraith", Foes, "27.Magane_Bozo", P8))
                    # (Line 99) GiveUnits(All, "40 + 1n Zergling", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Firebat", Foes, "27.Magane_Bozo", P8))
                    # (Line 100) GiveUnits(All, " Creep. Licht", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Zergling", Foes, "27.Magane_Bozo", P8))
                    # (Line 101) GiveUnits(All, "40 + 1n Drone", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, " Creep. Licht", Foes, "27.Magane_Bozo", P8))
                    # (Line 102) GiveUnits(All, "40 + 1n Mutalisk", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Drone", Foes, "27.Magane_Bozo", P8))
                    # (Line 103) GiveUnits(All, "40 + 1n Guardian", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Mutalisk", Foes, "27.Magane_Bozo", P8))
                    # (Line 104) GiveUnits(All, "40 + 1n Zealot", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Guardian", Foes, "27.Magane_Bozo", P8))
                    # (Line 105) GiveUnits(All, "40 + 3n Zeratul", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Zealot", Foes, "27.Magane_Bozo", P8))
                    # (Line 106) GiveUnits(All, "40 + 1n Mojo", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 3n Zeratul", Foes, "27.Magane_Bozo", P8))
                    # (Line 107) GiveUnits(All, "40 + 1n Gantrithor", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Mojo", Foes, "27.Magane_Bozo", P8))
                    # (Line 108) GiveUnits(All, "40 + 1n Lurker", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Gantrithor", Foes, "27.Magane_Bozo", P8))
                    # (Line 109) GiveUnits(All, "50 + 1n Tank", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "40 + 1n Lurker", Foes, "27.Magane_Bozo", P8))
                    # (Line 110) GiveUnits(All, "50 + 1n Battlecruiser", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "50 + 1n Tank", Foes, "27.Magane_Bozo", P8))
                    # (Line 111) GiveUnits(All, "60 + 3n Siege", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "50 + 1n Battlecruiser", Foes, "27.Magane_Bozo", P8))
                    # (Line 112) GiveUnits(All, "60 + 1n Siege", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 3n Siege", Foes, "27.Magane_Bozo", P8))
                    # (Line 113) GiveUnits(All, "60 + 1n Hydralisk", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 1n Siege", Foes, "27.Magane_Bozo", P8))
                    # (Line 114) GiveUnits(All, "60 + 1n Dragoon", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 1n Hydralisk", Foes, "27.Magane_Bozo", P8))
                    # (Line 115) GiveUnits(All, "60 + 1n High Templar", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 1n Dragoon", Foes, "27.Magane_Bozo", P8))
                    # (Line 116) GiveUnits(All, "60 + 1n Archon", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 1n High Templar", Foes, "27.Magane_Bozo", P8))
                    # (Line 117) GiveUnits(All, "60 + 1n Danimoth", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 1n Archon", Foes, "27.Magane_Bozo", P8))
                    # (Line 118) GiveUnits(All, "60 + 3n Ghost", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 1n Danimoth", Foes, "27.Magane_Bozo", P8))
                    # (Line 119) GiveUnits(All, "80 + 1n Goliath", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "60 + 3n Ghost", Foes, "27.Magane_Bozo", P8))
                    # (Line 120) GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Goliath", Foes, "27.Magane_Bozo", P8))
                    # (Line 121) GiveUnits(All, "80 + 1n Marine", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Vulture", Foes, "27.Magane_Bozo", P8))
                    # (Line 122) GiveUnits(All, "80 + 1n Tom Kazansky", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Marine", Foes, "27.Magane_Bozo", P8))
                    # (Line 123) GiveUnits(All, "80 + 1n Tank", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Tom Kazansky", Foes, "27.Magane_Bozo", P8))
                    # (Line 124) GiveUnits(All, "80 + 1n Mutalisk", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Tank", Foes, "27.Magane_Bozo", P8))
                    # (Line 125) GiveUnits(All, "80 + 1n Guardian", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Mutalisk", Foes, "27.Magane_Bozo", P8))
                    # (Line 126) GiveUnits(All, "80 + 1n Artanis", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Guardian", Foes, "27.Magane_Bozo", P8))
                    # (Line 127) GiveUnits(All, "80 + 1n Ghost", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Artanis", Foes, "27.Magane_Bozo", P8))
                    # (Line 128) GiveUnits(All, "100 + 1n Hyperion", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "80 + 1n Ghost", Foes, "27.Magane_Bozo", P8))
                    # (Line 129) GiveUnits(All, "100 + 1n Dragoon", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "100 + 1n Hyperion", Foes, "27.Magane_Bozo", P8))
                    # (Line 130) GiveUnits(All, "120 + 1n Archon", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "100 + 1n Dragoon", Foes, "27.Magane_Bozo", P8))
                    # (Line 131) GiveUnits(All, "130 + 1n Norad", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "120 + 1n Archon", Foes, "27.Magane_Bozo", P8))
                    # (Line 132) GiveUnits(All, "130 + 1n Arbiter", Foes, "27.Magane_Bozo", P8);
                    DoActions(GiveUnits(All, "130 + 1n Norad", Foes, "27.Magane_Bozo", P8))
                    # (Line 133) }
                    DoActions(GiveUnits(All, "130 + 1n Arbiter", Foes, "27.Magane_Bozo", P8))
                    # (Line 135) }
                EUDEndIf()
                # (Line 137) trg.Main_Wait(80);
            EUDEndIf()
            trg.Main_Wait(80)
            # (Line 139) if (v.P_LoopMain[playerID] == 19)
            if EUDIf()(v.P_LoopMain[playerID] == 19):
                # (Line 140) {
                # (Line 141) s.CharacterVoice(10);
                s.CharacterVoice(10)
                # (Line 142) }
                # (Line 144) v.P_LoopMain[playerID] += 1;
            EUDEndIf()
            _ARRW(v.P_LoopMain, playerID).__iadd__(1)
            # (Line 146) if (v.P_LoopMain[playerID] == 46)
            if EUDIf()(v.P_LoopMain[playerID] == 46):
                # (Line 147) {
                # (Line 148) v.P_CountMain[playerID] += 1;
                _ARRW(v.P_CountMain, playerID).__iadd__(1)
                # (Line 149) v.P_LoopMain[playerID] = 0;
                _ARRW(v.P_LoopMain, playerID) << (0)
                # (Line 150) }
                # (Line 151) }
            EUDEndIf()
            # (Line 152) else if (v.P_CountMain[playerID] == 2)
        if EUDElseIf()(v.P_CountMain[playerID] == 2):
            # (Line 153) {
            # (Line 154) KillUnitAt(All, "Protoss Dark Templar", "Anywhere", P7);
            # (Line 155) KillUnitAt(All, "80 + 1n Goliath", "Anywhere", P7);
            DoActions(KillUnitAt(All, "Protoss Dark Templar", "Anywhere", P7))
            # (Line 156) KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Goliath", "Anywhere", P7))
            # (Line 157) KillUnitAt(All, "80 + 1n Marine", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P7))
            # (Line 158) KillUnitAt(All, "80 + 1n Tom Kazansky", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Marine", "Anywhere", P7))
            # (Line 159) KillUnitAt(All, "80 + 1n Tank", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Tom Kazansky", "Anywhere", P7))
            # (Line 160) KillUnitAt(All, "80 + 1n Mutalisk", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Tank", "Anywhere", P7))
            # (Line 161) KillUnitAt(All, "80 + 1n Guardian", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Mutalisk", "Anywhere", P7))
            # (Line 162) KillUnitAt(All, "80 + 1n Artanis", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Guardian", "Anywhere", P7))
            # (Line 163) KillUnitAt(All, "80 + 1n Ghost", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Artanis", "Anywhere", P7))
            # (Line 164) KillUnitAt(All, "100 + 1n Hyperion", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Ghost", "Anywhere", P7))
            # (Line 165) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", P7);
            DoActions(KillUnitAt(All, "100 + 1n Hyperion", "Anywhere", P7))
            # (Line 166) KillUnitAt(All, "120 + 1n Archon", "Anywhere", P7);
            DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", P7))
            # (Line 167) KillUnitAt(All, "130 + 1n Norad", "Anywhere", P7);
            DoActions(KillUnitAt(All, "120 + 1n Archon", "Anywhere", P7))
            # (Line 168) KillUnitAt(All, "130 + 1n Arbiter", "Anywhere", P7);
            DoActions(KillUnitAt(All, "130 + 1n Norad", "Anywhere", P7))
            # (Line 169) KillUnitAt(All, "40 + 1n Marine", "Anywhere", P7);
            DoActions(KillUnitAt(All, "130 + 1n Arbiter", "Anywhere", P7))
            # (Line 170) KillUnitAt(All, "40 + 1n Ghost", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Marine", "Anywhere", P7))
            # (Line 171) KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Ghost", "Anywhere", P7))
            # (Line 172) KillUnitAt(All, "40 + 1n Goliath", "Anywhere", P7);
            DoActions(KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P7))
            # (Line 173) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Goliath", "Anywhere", P7))
            # (Line 174) KillUnitAt(All, "40 + 1n Firebat", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", P7))
            # (Line 175) KillUnitAt(All, "40 + 1n Zergling", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Firebat", "Anywhere", P7))
            # (Line 176) KillUnitAt(All, " Creep. Licht", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Zergling", "Anywhere", P7))
            # (Line 177) KillUnitAt(All, "40 + 1n Drone", "Anywhere", P7);
            DoActions(KillUnitAt(All, " Creep. Licht", "Anywhere", P7))
            # (Line 178) KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Drone", "Anywhere", P7))
            # (Line 179) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", P7))
            # (Line 180) KillUnitAt(All, "40 + 1n Zealot", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", P7))
            # (Line 181) KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Zealot", "Anywhere", P7))
            # (Line 182) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", P7))
            # (Line 183) KillUnitAt(All, "40 + 1n Gantrithor", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", P7))
            # (Line 184) KillUnitAt(All, "40 + 1n Lurker", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Gantrithor", "Anywhere", P7))
            # (Line 185) KillUnitAt(All, "50 + 1n Tank", "Anywhere", P7);
            DoActions(KillUnitAt(All, "40 + 1n Lurker", "Anywhere", P7))
            # (Line 186) KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", P7);
            DoActions(KillUnitAt(All, "50 + 1n Tank", "Anywhere", P7))
            # (Line 187) KillUnitAt(All, "60 + 3n Siege", "Anywhere", P7);
            DoActions(KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", P7))
            # (Line 188) KillUnitAt(All, "60 + 1n Siege", "Anywhere", P7);
            DoActions(KillUnitAt(All, "60 + 3n Siege", "Anywhere", P7))
            # (Line 189) KillUnitAt(All, "60 + 1n Hydralisk", "Anywhere", P7);
            DoActions(KillUnitAt(All, "60 + 1n Siege", "Anywhere", P7))
            # (Line 190) KillUnitAt(All, "60 + 1n Dragoon", "Anywhere", P7);
            DoActions(KillUnitAt(All, "60 + 1n Hydralisk", "Anywhere", P7))
            # (Line 191) KillUnitAt(All, "60 + 1n High Templar", "Anywhere", P7);
            DoActions(KillUnitAt(All, "60 + 1n Dragoon", "Anywhere", P7))
            # (Line 192) KillUnitAt(All, "60 + 1n Archon", "Anywhere", P7);
            DoActions(KillUnitAt(All, "60 + 1n High Templar", "Anywhere", P7))
            # (Line 193) KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", P7);
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", P7))
            # (Line 194) KillUnitAt(All, "60 + 3n Ghost", "Anywhere", P7);
            DoActions(KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", P7))
            # (Line 196) KillUnitAt(All, "Protoss Dark Templar", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 3n Ghost", "Anywhere", P7))
            # (Line 197) KillUnitAt(All, "80 + 1n Goliath", "Anywhere", P8);
            DoActions(KillUnitAt(All, "Protoss Dark Templar", "Anywhere", P8))
            # (Line 198) KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Goliath", "Anywhere", P8))
            # (Line 199) KillUnitAt(All, "80 + 1n Marine", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P8))
            # (Line 200) KillUnitAt(All, "80 + 1n Tom Kazansky", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Marine", "Anywhere", P8))
            # (Line 201) KillUnitAt(All, "80 + 1n Tank", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Tom Kazansky", "Anywhere", P8))
            # (Line 202) KillUnitAt(All, "80 + 1n Mutalisk", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Tank", "Anywhere", P8))
            # (Line 203) KillUnitAt(All, "80 + 1n Guardian", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Mutalisk", "Anywhere", P8))
            # (Line 204) KillUnitAt(All, "80 + 1n Artanis", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Guardian", "Anywhere", P8))
            # (Line 205) KillUnitAt(All, "80 + 1n Ghost", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Artanis", "Anywhere", P8))
            # (Line 206) KillUnitAt(All, "100 + 1n Hyperion", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Ghost", "Anywhere", P8))
            # (Line 207) KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", P8);
            DoActions(KillUnitAt(All, "100 + 1n Hyperion", "Anywhere", P8))
            # (Line 208) KillUnitAt(All, "120 + 1n Archon", "Anywhere", P8);
            DoActions(KillUnitAt(All, "100 + 1n Dragoon", "Anywhere", P8))
            # (Line 209) KillUnitAt(All, "130 + 1n Norad", "Anywhere", P8);
            DoActions(KillUnitAt(All, "120 + 1n Archon", "Anywhere", P8))
            # (Line 210) KillUnitAt(All, "130 + 1n Arbiter", "Anywhere", P8);
            DoActions(KillUnitAt(All, "130 + 1n Norad", "Anywhere", P8))
            # (Line 211) KillUnitAt(All, "40 + 1n Marine", "Anywhere", P8);
            DoActions(KillUnitAt(All, "130 + 1n Arbiter", "Anywhere", P8))
            # (Line 212) KillUnitAt(All, "40 + 1n Ghost", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Marine", "Anywhere", P8))
            # (Line 213) KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Ghost", "Anywhere", P8))
            # (Line 214) KillUnitAt(All, "40 + 1n Goliath", "Anywhere", P8);
            DoActions(KillUnitAt(All, "80 + 1n Vulture", "Anywhere", P8))
            # (Line 215) KillUnitAt(All, "40 + 1n Wraith", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Goliath", "Anywhere", P8))
            # (Line 216) KillUnitAt(All, "40 + 1n Firebat", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Wraith", "Anywhere", P8))
            # (Line 217) KillUnitAt(All, "40 + 1n Zergling", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Firebat", "Anywhere", P8))
            # (Line 218) KillUnitAt(All, " Creep. Licht", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Zergling", "Anywhere", P8))
            # (Line 219) KillUnitAt(All, "40 + 1n Drone", "Anywhere", P8);
            DoActions(KillUnitAt(All, " Creep. Licht", "Anywhere", P8))
            # (Line 220) KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Drone", "Anywhere", P8))
            # (Line 221) KillUnitAt(All, "40 + 1n Guardian", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Mutalisk", "Anywhere", P8))
            # (Line 222) KillUnitAt(All, "40 + 1n Zealot", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Guardian", "Anywhere", P8))
            # (Line 223) KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Zealot", "Anywhere", P8))
            # (Line 224) KillUnitAt(All, "40 + 1n Mojo", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 3n Zeratul", "Anywhere", P8))
            # (Line 225) KillUnitAt(All, "40 + 1n Gantrithor", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Mojo", "Anywhere", P8))
            # (Line 226) KillUnitAt(All, "40 + 1n Lurker", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Gantrithor", "Anywhere", P8))
            # (Line 227) KillUnitAt(All, "50 + 1n Tank", "Anywhere", P8);
            DoActions(KillUnitAt(All, "40 + 1n Lurker", "Anywhere", P8))
            # (Line 228) KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", P8);
            DoActions(KillUnitAt(All, "50 + 1n Tank", "Anywhere", P8))
            # (Line 229) KillUnitAt(All, "60 + 3n Siege", "Anywhere", P8);
            DoActions(KillUnitAt(All, "50 + 1n Battlecruiser", "Anywhere", P8))
            # (Line 230) KillUnitAt(All, "60 + 1n Siege", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 3n Siege", "Anywhere", P8))
            # (Line 231) KillUnitAt(All, "60 + 1n Hydralisk", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 1n Siege", "Anywhere", P8))
            # (Line 232) KillUnitAt(All, "60 + 1n Dragoon", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 1n Hydralisk", "Anywhere", P8))
            # (Line 233) KillUnitAt(All, "60 + 1n High Templar", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 1n Dragoon", "Anywhere", P8))
            # (Line 234) KillUnitAt(All, "60 + 1n Archon", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 1n High Templar", "Anywhere", P8))
            # (Line 235) KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 1n Archon", "Anywhere", P8))
            # (Line 236) KillUnitAt(All, "60 + 3n Ghost", "Anywhere", P8);
            DoActions(KillUnitAt(All, "60 + 1n Danimoth", "Anywhere", P8))
            # (Line 238) SetSwitch("Recall - Magane", Clear);
            DoActions(KillUnitAt(All, "60 + 3n Ghost", "Anywhere", P8))
            # (Line 239) SetDeaths(playerID, SetTo, 3600, " `UniqueCoolTime");
            DoActions(SetSwitch("Recall - Magane", Clear))
            # (Line 241) trg.SkillEnd();
            DoActions(SetDeaths(playerID, SetTo, 3600, " `UniqueCoolTime"))
            trg.SkillEnd()
            # (Line 242) }
            # (Line 243) }
        EUDEndIf()
        # (Line 244) }
    EUDEndIf()
